<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="patterneditor"
    nsURI="http:///de/uni_paderborn/fujaba/umlrt/patterneditor" nsPrefix="patterneditor">
  <eClassifiers xsi:type="ecore:EClass" name="PatternDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinationPattern" eType="ecore:EClass ../../de.uni_paderborn.fujaba.umlrt.model/model/umlrt.ecore#//uni_paderborn/fujaba/umlrt/model/pattern/CoordinationPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.umlrt.model/model/umlrt.ecore#//uni_paderborn/fujaba/umlrt/model/pattern/Role"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleConnectors" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.umlrt.model/model/umlrt.ecore#//uni_paderborn/fujaba/umlrt/model/pattern/RoleConnector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textualConstraints" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.umlrt.model/model/umlrt.ecore#//uni_paderborn/fujaba/umlrt/model/constraint/TextualConstraint"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
