<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="psm" nsURI="http://www.fujaba.de/muml/psm/0.4.0/" nsPrefix="psm">
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="allocation" nsURI="http://www.fujaba.de/muml/psm/allocation/0.4.0/"
      nsPrefix="allocation">
    <eClassifiers xsi:type="ecore:EClass" name="SystemAllocation" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocations" lowerBound="1"
          upperBound="-1" eType="#//allocation/Allocation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Allocation" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ComponentInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceInstance" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.hardware/model/hardware.ecore#//hwresourceinstance/StructuredResourceInstance"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="properties" nsURI="http://www.fujaba.de/muml/psm/properties/0.4.0/"
      nsPrefix="properties">
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceExecutionProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ComponentInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wcet" upperBound="-1"
          eType="#//properties/WCETpair" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeMem" upperBound="-1"
          eType="#//properties/MemoryPair" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ramMem" upperBound="-1"
          eType="#//properties/MemoryPair" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WCETpair">
      <eStructuralFeatures xsi:type="ecore:EReference" name="amount" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.hardware/model/hardware.ecore#//hwresourceinstance/StructuredResourceInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MemoryPair">
      <eStructuralFeatures xsi:type="ecore:EReference" name="amount" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.hardware/model/hardware.ecore#//hwvaluetype/DataSize"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.hardware/model/hardware.ecore#//hwresourceinstance/StructuredResourceInstance"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="realtimestatechart" nsURI="http://www.fujaba.de/muml/psm/realtimestatechart/0.4.0/"
      nsPrefix="realtimestatechart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The package extends the realtimestatechart-package of muml. Here a statechart with parameters is introdused."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedRealtimeStatechart" eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//realtimestatechart/RealtimeStatechart">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This class is a extension of a real-time statechart, which has aditional plattformspecific parameters."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//realtimestatechart/realtimestatechartparameter/RealtimeStatechartParameter"
          containment="true" eOpposite="#//realtimestatechart/realtimestatechartparameter/RealtimeStatechartParameter/statechart">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All parameter for this statechart."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allParameters" upperBound="-1"
          eType="#//realtimestatechart/realtimestatechartparameter/RealtimeStatechartParameter"
          volatile="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="derivation" value="self->closure(states.embeddedRegions.embeddedStatechart.oclAsType(realtimestatechart::ParameterizedRealtimeStatechart)).parameters->asOrderedSet()"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="APICall" eSuperTypes="../../de.uni_paderborn.fujaba.muml.actionlanguage/model/actionlanguage.ecore#//OperationCall">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This class represents a expression for a CallParameter. This Expression can be used within the realtimestatechart. It refers to the parameter, which is given to the realtimestatechart."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="apiCallSignature" lowerBound="1"
          eType="#//realtimestatechart/realtimestatechartparameter/APICallParameter"/>
    </eClassifiers>
    <eSubpackages name="realtimestatechartparameter" nsURI="http://www.fujaba.de/muml/psm/realtimestatechart/realtimestatechartparameter/0.1.0/"
        nsPrefix="realtimestatechartparameter">
      <eClassifiers xsi:type="ecore:EClass" name="APICallParameter" eSuperTypes="#//realtimestatechart/realtimestatechartparameter/RealtimeStatechartParameter ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Operation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="With this parameter a discrete port instance can insert a expression into its behavior described by a realtimestatechart."/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TimeParameter" eSuperTypes="#//realtimestatechart/realtimestatechartparameter/RealtimeStatechartParameter ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Variable">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="With this parameter a discrete port instance can insert a time value into its behavior described by a realtimestatechart."/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RealtimeStatechartParameter" abstract="true"
          eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement ../../org.storydriven.core/model/core.ecore#//CommentableElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents a parameter of a realtimestatechart, which can be bound by a instance of a discrete port. A parameter is used to add parts of a realtimestatechart that are only known in a instance of a discrete port."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" lowerBound="1"
            eType="#//realtimestatechart/ParameterizedRealtimeStatechart" eOpposite="#//realtimestatechart/ParameterizedRealtimeStatechart/parameters">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The statechart, to which this parameter belongs."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="realtimestatechartparameterbinding" nsURI="http://www.fujaba.de/muml/psm/realtimestatechart/realtimestatechartparameterbinding/0.1.0/"
        nsPrefix="realtimestatechartparameterbinding">
      <eClassifiers xsi:type="ecore:EClass" name="APICallParameterBinding" eSuperTypes="#//realtimestatechart/realtimestatechartparameterbinding/RealtimeStatechartParameterBinding ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Operation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="onlyCallParameterAllowed"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents a binding for a CallParameter. The parameter is bound to a concrete expression."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
            eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
            containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The expression, used for the parameter."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TimeParameterBinding" eSuperTypes="#//realtimestatechart/realtimestatechartparameterbinding/RealtimeStatechartParameterBinding">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="onlyTimeParameterAllowed"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents a binding for a TimeParameter. The parameter is bound to a concrete time value."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="timeValue" lowerBound="1"
            eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
            containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The time value used for the parameter."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RealtimeStatechartParameterBinding"
          abstract="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents a binding for a parameter of a realtimestatechart."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="portInstance" lowerBound="1"
            eType="#//instance/ParameterisableDiscreteSinglePortInstance" eOpposite="#//instance/ParameterisableDiscreteSinglePortInstance/bindings">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The instance of a discrete port."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
            eType="#//realtimestatechart/realtimestatechartparameter/RealtimeStatechartParameter">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The parameter, to which a concrete value will be assigned."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="api" nsURI="http://www.fujaba.de/muml/psm/api/0.4.0/" nsPrefix="api">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The software package contains the meta-model for specification a software platform. It can be used to describe the API of a concrete target platform.&#xD;&#xA;This package itself does not contain any class. Instead it contains more subpackages for different viewpoints."/>
    </eAnnotations>
    <eSubpackages name="portapimapping" nsURI="http://www.fujaba.de/muml/psm/api/portapimapping/0.4.0/"
        nsPrefix="portapimapping">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This package describes the informations that are needed to model a mapping from continuouse ports in MechatronicUML to api-commands. The ports of a continuourse component can be mapped to an expression, which can e.g. be a call of an api-command."/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="PortApiMapping" eSuperTypes="../../org.storydriven.core/model/core.ecore#//CommentableElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents the mapping of a muml-model. The continuous port from that model will be mapped to an expression, that should be executet, when the continuours ports send/recieve values."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
            eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ContinuousPortInstance">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The continuous port, that will be mapped to an expression."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="execCommand" lowerBound="1"
            eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
            containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The command to which a continuous port will be mapped. This command is executed each time, the continuous port is queried."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
            eType="#//api/portapimapping/MappingRepository" eOpposite="#//api/portapimapping/MappingRepository/portApiMappings">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The repository to which the mapping belongs."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initCommand" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
            containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="A optional command which has to be executed before any other api-command can be executed. For example some sonsors and actuators require an initial api-command."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MappingRepository" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement ../../org.storydriven.core/model/core.ecore#//CommentableElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class orders the mappings of a port. It is used to declare port mappings that assign api-commands to a conutinous port."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="portApiMappings" upperBound="-1"
            eType="#//api/portapimapping/PortApiMapping" containment="true" eOpposite="#//api/portapimapping/PortApiMapping/repository">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The mapping of a port, that assigns a api-command to a continuous port."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
            eType="#//Import" containment="true"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="apiexpressions" nsURI="http://www.fujaba.de/muml/psm/api/apiexpressions/0.4.0/"
        nsPrefix="apiexpressions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This package contains all expressions, which are used to model a call of an api-command with actual parameters."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
        <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
        <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="APICallExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="ParameterBindingForEveryParameter"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents an api call. It has an actual parameter for each formal parameter of an api-command. Inside an actual parameter a concrete value will be mapped to the formal parameters of an api-command from the swplatform-package."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="apiCommand" lowerBound="1"
            eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.swplatform/model/swplatform.ecore#//APICommand">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The APICommand to which this expression belongs."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBindings"
            upperBound="-1" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/ParameterBinding"
            containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The mapping where an actual parameter will be bound to a formal parameter."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumerationValueExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents an EnumerationValue at runtime. At runtime the Enumeration is bound to one of its possible values. This means, that a concrete EnumerationValue will be mapped to the Enumeration from the swplatform-package."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="enumValue" lowerBound="1"
            eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.swplatform/model/swplatform.ecore#//EnumerationValue">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The EnumerationValue to which this expression belongs."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ContinuousPortExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="OnlyInPortsAllowed"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class represents an expression, that contains a continuous port instance. In that way an api-command of an actuator can access the new value of the actuator."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="OnlyInPortsAllowed" value="self.continuousPort.portType.oclAsType(component::DirectedTypedPort).kind = component::PortDirectionKind::IN"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="continuousPort" lowerBound="1"
            eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ContinuousPortInstance">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The continuous port instance that belongs to the expression."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="instance" nsURI="http://www.fujaba.de/muml/psm/instance/0.4.0/"
      nsPrefix="instance">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The package extends the instance-package of muml. Here all parameters of a statechart will be bound within an instance of a discrete port."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterisableDiscreteSinglePortInstance"
        eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/DiscreteSinglePortInstance">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This class is a extension of a discrete port at instance level. The behavior of this port instance can have parameters. To these parameters this class defines parameter bindings."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//realtimestatechart/realtimestatechartparameterbinding/RealtimeStatechartParameterBinding"
          containment="true" eOpposite="#//realtimestatechart/realtimestatechartparameterbinding/RealtimeStatechartParameterBinding/portInstance">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The parameter bindings for each parameter of the statechart of the port."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
