/*
 * generated by Xtext
 */
package org.muml.pm.software.oslanguage;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.muml.pm.software.platform.oslanguage.valueconverter.SWPlatformTerminalConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OperatingSystemLanguageRuntimeModule extends org.muml.pm.software.platform.oslanguage.AbstractOperatingSystemLanguageRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		// TODO Auto-generated method stub
		return SWPlatformTerminalConverter.class;
	}

}
