/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.muml.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ActionLanguageTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
