/*
 * generated by Xtext
 */
package org.muml.graphviz.plain.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGraphvizPlainValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.muml.org/graphviz/plain/1.0.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.muml.org/graphviz/util/1.0.0"));
		return result;
	}
}
