<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deployment"
    nsURI="http://deployment/1.0" nsPrefix="deployment">
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareNodes" lowerBound="1"
        upperBound="-1" eType="#//HardwareNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstanceConfiguration"
        lowerBound="1" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/instance/ComponentInstanceConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLinks" upperBound="-1"
        eType="#//CommunicationLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/instance/ComponentInstance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwarePorts" upperBound="-1"
        eType="#//HardwarePort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstanceOfNode"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/instance/ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwarePort"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwarePort" lowerBound="1"
        eType="#//HardwarePort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstancePort"
        lowerBound="1" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/instance/PortInstance"/>
  </eClassifiers>
</ecore:EPackage>
