/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.graphviz.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PlainUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.uni_paderborn.fujaba.graphviz.xtext.ui.internal.PlainActivator.getInstance().getInjector("de.uni_paderborn.fujaba.graphviz.xtext.Plain");
	}
	
}
