#ifndef MUML_DDS_IDL
#define MUML_DDS_IDL

  struct DDS_M1completeDeny_M1;
  struct DDS_M1accessGranted_M1;
  struct DDS_M1launchCode_M1;
  struct DDS_M1ready_M1;
  struct DDS_M1accessDenied_M1;
  struct DDS_M1otherReady_M1;

#pragma DCPS_DATA_TYPE "DDS_M1completeDeny_M1"
  struct DDS_M1completeDeny_M1 {
    char dummy;
  };

#pragma DCPS_DATA_TYPE "DDS_M1accessGranted_M1"
  struct DDS_M1accessGranted_M1 {
    char dummy;
  };

#pragma DCPS_DATA_TYPE "DDS_M1launchCode_M1"
  struct DDS_M1launchCode_M1 {
    long id;
  };

#pragma DCPS_DATA_TYPE "DDS_M1ready_M1"
  struct DDS_M1ready_M1 {
    char dummy;
  };

#pragma DCPS_DATA_TYPE "DDS_M1accessDenied_M1"
  struct DDS_M1accessDenied_M1 {
    char dummy;
  };

#pragma DCPS_DATA_TYPE "DDS_M1otherReady_M1"
  struct DDS_M1otherReady_M1 {
    char dummy;
  };
#endif 
