/*
 * generated by Xtext
 */
package org.muml.reconfigurationverification.fotctl.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.muml.reconfigurationverification.fotctl.xtext.ui.internal.FOTCTLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FOTCTLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FOTCTLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FOTCTLActivator.getInstance().getInjector(FOTCTLActivator.ORG_MUML_RECONFIGURATIONVERIFICATION_FOTCTL_XTEXT_FOTCTL);
	}
	
}
