<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codegen" nsURI="http://www.fujaba.de/muml/psm/codegen/0.1.0"
    nsPrefix="codegen">
  <eClassifiers xsi:type="ecore:EClass" name="RefinedComponentInstance" abstract="true"
      eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ComponentInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefinedAtomicComponentInstance" eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/AtomicComponentInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedResourceInstance"
        lowerBound="1" eType="#//RefindedStructuredResourceInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefindedStructuredResourceInstance"
      eSuperTypes="../../de.uni_paderborn.fujaba.muml.hardware/model/hardware.ecore#//platform/StructuredResourceInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedAtomicComponentInstances"
        upperBound="-1" eType="#//RefinedAtomicComponentInstance"/>
  </eClassifiers>
</ecore:EPackage>
