/*
 * generated by Xtext
 */
package org.muml.psm.allocation.ilp.lpsolve.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LPSolveRuntimeModule extends org.muml.psm.allocation.ilp.lpsolve.xtext.AbstractLPSolveRuntimeModule {

}
