<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="realtimeStatechart"
    nsURI="http://uni_paderborn/fujaba/umlrt/realtimeStatechart" nsPrefix="realtimeStatechart">
  <eClassifiers xsi:type="ecore:EClass" name="RealtimeStatechart" eSuperTypes="../../de.uni_paderborn.fujaba.umlrt.model/model/umlrt.ecore#//uni_paderborn/fujaba/umlrt/model/realtimestatechart/FujabaRealtimeStatechart"/>
</ecore:EPackage>
