<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reconfiguration" nsURI="http://www.fujaba.de/muml/reconfiguration/0.3.18"
    nsPrefix="reconfiguration">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This package contains all classes which are needed to define reconfigurable components in MechatronicUML. A reconfigurable component may change its ports and, in case of a structured component, its inner structure. The supported structural changes include adding or removing embedded component instances, adding or removing port instances, adding or removing or redirecting assemblies and delegations."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurableStructuredComponent" eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//component/StructuredComponent #//ReconfigurableComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A reconfigurable structured component may change its internal structure at run-time. Therefore, it may instantiate or remove component instances that are typed over embedded component parts. In addition, assemblies and delegations in the structured component may be added, removed or redirected. The reconfiguration behavior in encapsulated in the reconfiguration controllers which are contained in the reconfigurable structured component."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" ordered="false"
        eType="#//Controller" containment="true" eOpposite="#//Controller/structuredComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" eType="#//Manager"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if self.controller.oclIsKindOf(RuleBasedReconfigurationController) then self.controller.oclAsType(RuleBasedReconfigurationController).manager else null endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" eType="#//Executor"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if self.controller.oclIsKindOf(RuleBasedReconfigurationController) then self.controller.oclAsType(RuleBasedReconfigurationController).executor else null endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialConfiguration" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ComponentInstanceConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationPort" abstract="true"
      eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//component/DiscretePort">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A reconfiguration port defines the external interface for accessing the reconfiguration capabilities of a reconfigurable structured component. In case of a reconfigurable structured component, they are delegated to one of the controllers of the component. In case of a reconfigurable atomic component, the reconfiguration port is directly implemented."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" abstract="true" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/BehavioralElement ../../org.storydriven.core/model/core.ecore#//CommentableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Controllers add additional behavior to a reconfigurable behavior. Since the behavior of the structured component is, in principle, defined by the execution of its embedded components, it has no own behavior specification. We use Controllers to add behavior that may access the embedded components of a structured components and use them, e.g., for specifying reconfiguration behavior."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuredComponent" lowerBound="1"
        eType="#//ReconfigurableStructuredComponent" eOpposite="#//ReconfigurableStructuredComponent/controller"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manager" eSuperTypes="../../org.storydriven.core/model/core.ecore#//CommentableElement ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/BehavioralElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Manager is responsible for defining when to execute which reconfiguration rule. &#xD;&#xA;It reacts to reconfiguration messages that are provided by embedded components and indicate that a certain situation which may require reconfiguration has been monitored. &#xD;&#xA;The Manager is part of a RuleBasedReconfigurationController. Therefore, it provides a rule-based specification of its behavior using a set of ManagerSpecificationEntries."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificationEntries" upperBound="-1"
        eType="#//ManagerSpecificationEntry" containment="true" eOpposite="#//ManagerSpecificationEntry/manager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationController"
        lowerBound="1" eType="#//RuleBasedReconfigurationController" eOpposite="#//RuleBasedReconfigurationController/manager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//component/DiscretePort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationMessagePorts"
        upperBound="-1" eType="#//ReconfigurationMessagePort" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="self.ports -> select(p | p.oclIsTypeOf(ReconfigurationMessagePort))"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executor" eSuperTypes="../../org.storydriven.core/model/core.ecore#//CommentableElement ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/BehavioralElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Executor is responsible for executing reconfigurations in a reconfigurable component. It is part of a RuleBasedReconfigurationController and defines a set of ReconfigurationRules that it can execute."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificationEntries" lowerBound="1"
        upperBound="-1" eType="#//ExecutorSpecificationEntry" containment="true" eOpposite="#//ExecutorSpecificationEntry/executor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationController"
        lowerBound="1" eType="#//RuleBasedReconfigurationController" eOpposite="#//RuleBasedReconfigurationController/executor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//component/DiscretePort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationExecutionPorts"
        upperBound="-1" eType="#//ReconfigurationExecutionPort" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="self.ports -> select(p | p.oclIsTypeOf(ReconfigurationExecutionPort))"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationRule" abstract="true"
      eSuperTypes="../../org.storydriven.core/model/core.ecore#//CommentableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A reconfiguration rule describes a modification of the internal structure of a reconfigurable structured component or of a reconfigurable atomic component. It has a Signature that defines the name of the reconfiguration rule as well as its input and output parameters."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfiguredComponent"
        eType="#//ReconfigurableComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wcet" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="#//Signature" containment="true" eOpposite="#//Signature/reconfigurationRule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if self.signature.oclIsUndefined() then null else self.signature.name endif"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralCondition" abstract="true"
      eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement ../../org.storydriven.core/model/core.ecore#//CommentableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A StructuralCondition is a condition on the embedded component instances of a reconfigurable structured component instance that is used by a ManagerSpecificationEntry for deciding whether a reconfiguration may be executed."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Parameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurableComponent" abstract="true"
      eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//component/Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This abstract class needs to be implemented by all reconfigurable component types in order to distinguish them from static component types."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationMessagePort" eSuperTypes="#//ReconfigurationPort">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A component uses its ReconfigurationMessagePorts for sending information on situations that may require a reconfiguration to its parent. Consequently, RM ports are used for bottom-up information provision.&#xD;&#xA;The ReconfigurationMessagePorts are implemented in the Manager if a RuleBasedReconfigurationController is used."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceEntries" upperBound="-1"
        eType="#//ReconfigurationMessagePortInterfaceEntry" containment="true" eOpposite="#//ReconfigurationMessagePortInterfaceEntry/reconfigurationMessagePort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationExecutionPort" eSuperTypes="#//ReconfigurationPort">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A component uses its ReconfigurationExecutionPorts for offering reconfiguration operations to its parent. The parent may trigger a reconfiguration operation on a child by sending a reconfiguration message to the ReconfigurationExecutionPort of that child. Thus, ReconfigurationExecutionPorts  are primarily used for top-down reconfiguration initiation. They are implemented by the Executor if a RuleBasedReconfigurationController is used."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceEntries" upperBound="-1"
        eType="#//ReconfigurationExecutionPortInterfaceEntry" containment="true" eOpposite="#//ReconfigurationExecutionPortInterfaceEntry/reconfigurationExecutionPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutorSpecificationEntry" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An ExecutorSpecificationEntry defines a ReconfigurationRule."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" lowerBound="1"
        eType="#//Executor" eOpposite="#//Executor/specificationEntries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationRule" lowerBound="1"
        eType="#//ReconfigurationRule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManagerSpecificationEntry" eSuperTypes="../../org.storydriven.core/model/core.ecore#//CommentableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Each ManagerSpecificationEntry defines the reaction of the manager to a reconfiguration message which has either been sent by an embedded child or which is received from the executor as part of a hierarchical reconfiguration."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="treat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propagate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" lowerBound="1"
        eType="#//Manager" eOpposite="#//Manager/specificationEntries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageType" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//msgtype/MessageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralCondition" eType="#//StructuralCondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationRule" eType="#//ReconfigurationRule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invokePlanner" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeForPlanning" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationController" abstract="true"
      eSuperTypes="#//Controller">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Reconfiguration controllers encapsulate the reconfiguration behavior of a reconfigurable structured component.&#xD;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleBasedReconfigurationController"
      eSuperTypes="#//ReconfigurationController">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A RuleBasedReconfigurationController uses a declarative approach for defining the reconfiguration behavior. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" lowerBound="1"
        eType="#//Executor" containment="true" eOpposite="#//Executor/reconfigurationController"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" lowerBound="1"
        eType="#//Manager" containment="true" eOpposite="#//Manager/reconfigurationController"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationPortInterfaceEntry" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ReconfigurationPortInterfaceEntry is the abstract super class of the interface entries of ReconfigurationMessagePorts and ReconfigurationExecutionPorts."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageType" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//msgtype/MessageType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationMessagePortInterfaceEntry"
      eSuperTypes="#//ReconfigurationPortInterfaceEntry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Each ReconfigurationMessagePortInterfaceEntry defines one reconfiguration message that is sent by a component to its parent. In addition to the message, it defines the ReconfigurationmessageType and, in case that it is a request, the expected response time for the parent."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reconfigurationMessageType"
        eType="#//ReconfigurationMessageTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expectedResponseTime" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationMessagePort"
        lowerBound="1" eType="#//ReconfigurationMessagePort" eOpposite="#//ReconfigurationMessagePort/interfaceEntries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReconfigurationMessageTypeEnum">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="If a reconfiguration message is sent by an embedded child, we distinguish to types of reconfiguration messages. These are info messages and requests. An info message just indicates that a certain situation has been monitored. A request is used if the embedded component knows that a reconfiguration needs to be performed, but it cannot perform the reconfiguration itself. A request needs to be answered by the parent component, an info message is not answered."/>
    </eAnnotations>
    <eLiterals name="INFO" literal="INFO"/>
    <eLiterals name="REQUEST" value="1" literal="REQUEST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationExecutionPortInterfaceEntry"
      eSuperTypes="#//ReconfigurationPortInterfaceEntry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Each ReconfigurationExecutionPortInterfaceEntry defines one reconfiguration message that may be sent by the parent component to initiate a reconfiguration on the component. &#xD;&#xA;In addition to the message, it defines the duration for deciding whether the requested reconfiguration can be executed and the duration for executing the reconfiguration."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeForDecision" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeForExecution" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationExecutionPort"
        lowerBound="1" eType="#//ReconfigurationExecutionPort" eOpposite="#//ReconfigurationExecutionPort/interfaceEntries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The class Signature defines the signature of a ReconfigurationRule. It defines the name of the ReconfigurationRule and its input and output parameters."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnParameters" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationRule" lowerBound="1"
        eType="#//ReconfigurationRule" eOpposite="#//ReconfigurationRule/signature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalReconfigurationCommunicationPort"
      eSuperTypes="#//ReconfigurationPort">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An InternalReconfigurationCommunicationPort is used for the interaction&#xD;&#xA;of manager and executor within a structured component. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationPortAssemblyConnector"
      eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//component/PortConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ReconfigurationPortAssemblyConnector connects two ReconfigurationPorts with each other.&#xD;&#xA;In contrast to a normal assembly used for component parts within a structured&#xD;&#xA;component, the ReconfigurationPortAssemblyConnector connects two&#xD;&#xA;reconfiguration ports instead of two port parts."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationPortDelegationConnector"
      eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//component/PortConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ReconfigurationPortDelegationConnector connects two ReconfigurationPorts with each other.&#xD;&#xA;In contrast to a normal delegation connector used for component parts within a structured&#xD;&#xA;component, the ReconfigurationPortDelegationConnector connects two&#xD;&#xA;reconfiguration ports instead of one port and one port part."/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="expression" nsURI="http://www.fujaba.de/muml/reconfiguration/expression/0.3.7"
      nsPrefix="expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This package defines expressions that may used for calling reconfiguration operations&#xD;&#xA;in the action language."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityCallExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression ../../org.storydriven.storydiagrams/model/storydiagrams.ecore#//calls/Invocation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An ActivityCallExpression can be used for calling a story diagram from an expression specified by the MechatronicUML action language. &#xD;&#xA;In particular, it may be used for calling a story diagram in the action of a transition of a real-time statechart."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          eType="ecore:EClass ../../org.storydriven.storydiagrams/model/storydiagrams.ecore#//activities/Activity"
          volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="derivation" value="self.callee.oclAsType(storydiagrams::activities::Activity)"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReconfigurationRuleCallExpression"
        eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A ReconfigurationRuleCallExpression can be used for calling a ReconfigurationRule from an expression specified by the MechatronicUML action language. &#xD;&#xA;In particular, it may be used for calling a reconfiguration rule in the action of a transition of a real-time statechart."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reconfigurationRule"
          lowerBound="1" eType="#//ReconfigurationRule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBindings" upperBound="-1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/ParameterBinding"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="structdatatype" nsURI="http://www.fujaba.de/muml/reconfiguration/structdatatype/0.3.18"
      nsPrefix="structdatatype">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This package defines complex struct data types that are used by the&#xD;&#xA;reconfiguration behavior. "/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="StructType" eSuperTypes="../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//types/DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A StructType is a complex data type which is comparable to a struct in C. It specifies a set of attributes and a set of references, but provides no inheritance."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#//structdatatype/Attribute" containment="true" eOpposite="#//structdatatype/Attribute/structType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
          eType="#//structdatatype/Reference" containment="true" eOpposite="#//structdatatype/Reference/structType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An attribute is a field of a StructType. An attribute specifies a name and a primitive or array data type."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="structType" lowerBound="1"
          eType="#//structdatatype/StructType" eOpposite="#//structdatatype/StructType/attributes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//types/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A reference is a field of a StructType. It specifies a relation to another StructType or an element of the MechatronicUML meta-model such as a component or port. &#xD;&#xA;A reference specifies a cardinality that defines the minimum and maximum number of elements that need to be referenced."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="structType" lowerBound="1"
          eType="#//structdatatype/StructType" eOpposite="#//structdatatype/StructType/references"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/Cardinality"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//types/DataType"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
