/*
 * generated by Xtext
 */
package org.muml.pm.software.platform.oslanguage.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.muml.pm.software.platform.oslanguage.ui.internal.OperatingSystemLanguageActivator;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OperatingSystemLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OperatingSystemLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OperatingSystemLanguageActivator.getInstance().getInjector(OperatingSystemLanguageActivator.DE_UNI_PADERBORN_FUJABA_MUML_SWPLATFORM_OSLANGUAGE_OPERATINGSYSTEMLANGUAGE);
	}
	
}
