/*
 * generated by Fujaba - CodeGen2
 */

package de.uni_paderborn.fujaba.umlrt.model.part;


import de.uni_paderborn.fujaba.umlrt.model.component.ProvidedInterface;


/**
 * @author chrome
 * @author Last editor: $Author: chrome $
 * @version $Revision: 2793 $ $Date: 2008-01-17 21:34:37 +0100 (Do, 17 Jan 2008) $
 * 
 * @model
 */
public interface ProvidedInterfacePart extends InterfacePart
{
//	/**
//	 * @model
//	 */
//   public java.util.List<ProvidedInterfaceVariable> getInterfaceVariables();

	/**
	 * @model
	 */
   public ProvidedInterface getProvidedInterface();

}

/*
 * $Log$
 * Revision 1.6  2008/01/17 20:34:37  chrome
 * - introduced InterfaceVariables
 * - association InterfacePart <-> Interface changed to unidirectional
 * Revision 1.5 2007/12/10 20:24:47 chrome added associations
 * between Part- and Instance-classes Revision 1.4 2007/11/18 18:14:08 chrome - changed role names
 * requiredIFPortVariable => sourcePortVariable, providedIFPortVariable => targetPortVariable (more
 * generalized approach) - added abstract ConnectorLink to be specialized by Assembly- and
 * DelegationLink - introduced DelegationLink (temporarily without asso to DelegationType because of
 * Codegen problems) Revision 1.3 2007/11/09 10:53:25 chrome introduced AssemblyLink Revision 1.2
 * 2007/10/27 13:59:38 chrome changed many associations to compositions - Delegation- and
 * AssemlblyTypes are deleted if related Port(-Parts) are deleted - Deleting a Component results in
 * deleting all embedded and referencing Parts and ConnectorTypes Revision 1.1 2007/10/19 13:37:35
 * chrome changed package structure
 * 
 * Revision 1.1 2007/10/11 15:30:31 chrome First buggy version of ComponentParts
 * 
 */