/*
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.muml.allocation.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AllocationSpecificationLanguageUiModule extends de.uni_paderborn.fujaba.muml.allocation.language.ui.AbstractAllocationSpecificationLanguageUiModule {
	public AllocationSpecificationLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
