/*
* generated by Xtext
*/
package org.muml.psm.api.apimappinglanguage.xtext.validation;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class APIMappingLanguageJavaValidator extends org.muml.psm.api.apimappinglanguage.xtext.validation.AbstractAPIMappingLanguageJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}
}
