/**
 *
 * $Id$
 */
package de.uni_paderborn.uppaal.validation;

import de.uni_paderborn.uppaal.declarations.GlobalDeclarations;
import de.uni_paderborn.uppaal.declarations.SystemDeclarations;

import de.uni_paderborn.uppaal.templates.Template;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_paderborn.uppaal.NTA}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NTAValidator {
	boolean validate();

	boolean validateGlobalDeclarations(GlobalDeclarations value);
	boolean validateTemplate(EList<Template> value);
	boolean validateSystemDeclarations(SystemDeclarations value);
}
