/*
 * generated by Xtext
 */
package org.muml.graphviz.dot.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DotLanguageUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.muml.graphviz.dot.xtext.ui.internal.DotLanguageActivator.getInstance().getInjector("de.uni_paderborn.fujaba.graphviz.dot.xtext.DotLanguage");
	}
	
}
