<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ilp" nsURI="http://www.muml.org/psm/allocation/ilp/1.0.0" nsPrefix="ilp">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This package contains all classes for modeling an Integer Linear Program."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLinearProgram">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents an Integer Linear Program. It contains all variables,&#xA;linear constraints and a linear optimization function."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variables that are used in this Integer Linear Program."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ConstraintExpression" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraints expressions for this Integer Linear Program"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectiveFunction" eType="#//ObjectiveFunctionExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The objective funtion to which is to be minimized or maximized of this Integer Linear Program."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="../../org.muml.core/model/core.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a variable, which is used in an Integer Linear Program."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//ILPDataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Determines the data type of the variable."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ILPDataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This enumeration provides values for a Variable's data type."/>
    </eAnnotations>
    <eLiterals name="BINARY"/>
    <eLiterals name="INTEGER" value="1"/>
    <eLiterals name="REAL" value="2" literal="REAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintExpression" eSuperTypes="../../org.muml.core/model/core.ecore#//expressions/common/ComparisonExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a constraint of the Integer Linear Program."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidOperator"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="ValidOperator" value="-- Invalid comparison operator (allowed &lt;, &lt;=, =, >=, >)&#xA;Set{core::expressions::common::ComparingOperator::LESS, core::expressions::common::ComparingOperator::LESS_OR_EQUAL, core::expressions::common::ComparingOperator::EQUAL, core::expressions::common::ComparingOperator::GREATER_OR_EQUAL, core::expressions::common::ComparingOperator::GREATER}->includes(operator)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExpression" eSuperTypes="../../org.muml.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class references a variable, which is used in a ConstraintExpression or&#xA;ObjectiveFunctionExpression."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variable to which this VariableExpression references."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectiveFunctionExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents an Integer Linear Program's objective function.&#xA;The Integer Linear Program will be maximzed or minimized to this function."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goal" lowerBound="1" eType="#//ObjectiveGoal"
        defaultValueLiteral="MAX">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Determines whether the objective function shall be minimized or maximized."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectiveFunction" lowerBound="1"
        eType="ecore:EClass ../../org.muml.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectiveGoal">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This enumeration provides values for an ObjectiveFunctionExpression's goal."/>
    </eAnnotations>
    <eLiterals name="MIN"/>
    <eLiterals name="MAX" value="1"/>
  </eClassifiers>
</ecore:EPackage>
