<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="actionlanguage" nsURI="http://www.fujaba.de/muml/actionlanguage/0.4.0"
    nsPrefix="actionlanguage">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The base package for the muml action language. It is an extension to the core.ecore expression package.&#xD;&#xA;The action language contains block definition, control structures like conditional statements and loops, assignments, and variable and operation call expressions. "/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="AssignOperator">
    <eLiterals name="UNSET" literal="UNSET"/>
    <eLiterals name="ASSIGN" value="1" literal=":="/>
    <eLiterals name="PLUS_EQUAL" value="2" literal="+="/>
    <eLiterals name="EQUAL_PLUS" value="3" literal="=+"/>
    <eLiterals name="MINUS_EQUAL" value="4" literal="-="/>
    <eLiterals name="EQUAL_MINUS" value="5" literal="=-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IncrementDecrementOperator">
    <eLiterals name="UNSET" literal="UNSET"/>
    <eLiterals name="INCREMENT" value="2" literal="++"/>
    <eLiterals name="DECREMENT" value="1" literal="--"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A block is used to group expressions. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of expressions may be attached as a body of a loop or represent a path of a conditional statement."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" abstract="true" eSuperTypes="#//Block">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A loop statement executed a block until the Boolean value of loop test expression is false."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Body block of the loop."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopTest" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If the loop test expression evaluates to true the block is executed. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileLoop" eSuperTypes="#//Loop">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The while statement first evaluates the loop test expression and afterwards if the expression evaluates to true it executes the block. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoWhileLoop" eSuperTypes="#//Loop">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The do while statement first executes the block and afterwards it evaluates the loop test expression. If the expression evaluates to true it executes the block again. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An assignment is used to assign a value to a variable. "/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidLHS"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="ValidLHS" value="-- a hybrid in port is not allowed as a lhs of an assignment&#xA;let lhs : TypedNamedElementExpression = lhs_typedNamedElementExpression&#xA;in&#xA;if not lhs.oclIsUndefined() and lhs.typedNamedElement.oclIsKindOf(component::HybridPort) then&#xA;&#x9;lhs.typedNamedElement.oclAsType(component::HybridPort).outPort&#xA;else&#xA;&#x9;true&#xA;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignOperator" eType="#//AssignOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An assignment is used to assign a value to a variable. A simple assignment is one made using the \emph{&lt;ASSIGN>} Operator \emph{':='}. Further, we have  four more assign operators which are used as abbreviated syntax form. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs_assignExpression" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The right-hand-side expression evaluates to a value which is assigned to the left-hand-side variable."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incrementDecrementOperator"
        eType="#//IncrementDecrementOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abbreviated form of x := x+1; or x :=x-1."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs_typedNamedElementExpression"
        eType="#//TypedNamedElementExpression" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=" The left-hand-side of an assignment must be a single variable and must not be another expression."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoop" eSuperTypes="#//Loop">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The for loop statement firstly initialize a loop variable by the initialize expression and assigning on each loop run afterwards a loop variable by the counting expression to successive values of a sequence."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializeExpression" eType="#//Assignment"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Initialize a loop variable by the initialize expression."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countingExpression" eType="#//Assignment"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Assigning on each loop run afterwards a loop variable by the counting expression to successive values of a sequence."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An if statement is used if the referenced block should be executed only when the condition expression evaluates to true.&#xD;&#xA;An if statement always have one if-condition and one corresponding if-block, any number of else-if-conditions and corresponding else-if-blocks and at most one else-block. &#xD;&#xA; "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifCondition" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If condition of the if statement."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifBlock" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Block which is executed if the if condition evaluates to true."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfConditions" upperBound="-1"
        eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ElseIf condition of the if statement."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfBlocks" upperBound="-1"
        eType="#//Block" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Block which is executed if the corresponding elseif condition evaluates to true."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="#//Block"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Block which is executed if no if or elseif condition evaluates to true."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationCall" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Operation calls are used to call an operation with concrete parameter bindings. "/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="AllParametersMustBeBound" value="-- An OperationCall must bind a value to every parameter&#xA;not operation.oclIsUndefined() implies &#xA;operation.parameters->asSet() = parameterBinding.parameter->asSet()&#xA;-- author: bingo"/>
      <details key="UniqueParameterBindings" value="-- An OperationCall must not bind multiple values to any parameter&#xA;parameterBinding->isUnique(parameter)&#xA;-- author: bingo"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AllParametersMustBeBound UniqueParameterBindings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Operation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Operation which belongs to an operation call."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBinding" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/ParameterBinding"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Parameter bindings which belongs to an operation call."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The return statement specifies the return expression of an operation call. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return expression which blongs to a return statement."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerMessageExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a parameter of a transition's trigger message."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageType" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//msgtype/MessageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreteInteractionEndpointReference"
      eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A DiscreteInteractionEndpointReference is used for defining SelectorExpressions&#xD;&#xA;in a multi-role or multi-port. There, a SelectorExpression may reference a&#xD;&#xA;sub-role instance or sub-port instance for selecting the synchronization partner. &#xD;&#xA;The DiscreteInteractionEndpointReference always specifies a PositionSelector that&#xD;&#xA;defines the position of the reference sub-role instance or sub-port instance. It may, &#xD;&#xA;e.g., be the first or last one in a multi-role or multi-port. The reference &#xD;&#xA;typedNamedElementExpressions allows to reference a variable containing a &#xD;&#xA;sub-role instance or a sub-port instance. In combination, both references enable&#xD;&#xA;to select the next or previous sub-role (or sub-port) instance, e.g., as var1.next. In &#xD;&#xA;this case, next is the PositionSelector while var1 is the typedNamedElementExpression."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedNamedElementExpression"
        eType="#//TypedNamedElementExpression" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allows to reference a variable containing a sub-role instance of sub-port instance.&#xD;&#xA;This field is optional. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
        eType="#//PositionSelector" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the relative position of the sub-role instance or sub-port instance.&#xD;&#xA;In particular, it enables to select the first or last sub-role instance (sub-port instance) of a &#xD;&#xA;multi-role instance (multi-port instance) using keyword first and last, to select itself&#xD;&#xA;in case of a sub-role instance (sub-port instance) using keyword self, or the next&#xD;&#xA;or previous sub-role given a reference either by self or a variable using keywords&#xD;&#xA;next and prev."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PositionSelectorKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines keywords for referring to sub-role instance (sub-port instances) of a&#xD;&#xA;multi-role instance (multi-port instance). Self may be used by a sub-role&#xD;&#xA;instance (sub-port instance) and refers to the corresponding sub-role instance&#xD;&#xA;(sub-port instance) itself. First and last may be used by the adaptation behavior&#xD;&#xA;and refer to the first or last sub-role instance (sub-port instance) of the multi-role&#xD;&#xA;instance (multi-port instance). Given a reference sub-role instance (sub-port&#xD;&#xA;instance), next and prev refer to the next or previous sub-role instance (sub-port&#xD;&#xA;instance). If the reference sub-role instance (sub-port instance) is the last one &#xD;&#xA;(first one), then next (first) refers to null."/>
    </eAnnotations>
    <eLiterals name="SELF"/>
    <eLiterals name="FIRST" value="1"/>
    <eLiterals name="LAST" value="2"/>
    <eLiterals name="PREV" value="3" literal="PREV"/>
    <eLiterals name="NEXT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositionSelector" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a relative position of a sub-role instance or sub-port instance.&#xD;&#xA;The kind defines the particular reference using an enum literal where&#xD;&#xA;self refers to a sub-role instance (sub-port instance) itself, first or last refer to the&#xD;&#xA;first or last sub-role instance (sub-port instance) or a multi-role instance (multi-port&#xD;&#xA;instance), and next or prev refer to the next or previous sub-role instance (sub-port&#xD;&#xA;instance). PositionSelectors can be concatenated using the successor reference.&#xD;&#xA;That enables to specify, e.g., self.next, first.next, or self.prev.prev."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//PositionSelectorKind">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The enum literal defining the position."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="#//PositionSelector"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Successors of a PositionSelector enable to concatenate PositionSelectors for&#xD;&#xA;specifying more complex expression like self.next or self.prev.prev."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariableDeclarationStatement" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="UniqueName" value="-- check if no variable with the same name was defined before&#xA;self.allSurroundingBlocks->collect(&#xA;&#x9;expressions&#xA;)->select(&#xA;&#x9;oclIsKindOf(LocalVariableDeclarationStatement)&#xA;)->collect(&#xA;&#x9;oclAsType(LocalVariableDeclarationStatement)&#xA;)->one(&#xA;&#x9;variable.name = self.variable.name&#xA;)"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enables to declare a local variable inside a Block. Local variables are declared &#xD;&#xA;according to the C-rule and have the scope of the block they are defined in.&#xD;&#xA;Local variables may not have the same name as a variable that is declared in the&#xD;&#xA;real-time statechart."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/Variable"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variable that is declared and optionally initialized by this declaration &#xD;&#xA;statement."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allSurroundingBlocks" upperBound="-1"
        eType="#//Block" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="-- collect all blocks which surround this LocalVariableDeclarationStatement&#xA;self.eContainer()->closure(c : ecore::EObject |&#xA;&#x9;if c.eContainer().oclIsKindOf(core::expressions::Expression) then&#xA;&#x9;&#x9;c.eContainer()&#xA;&#x9;else&#xA;&#x9;&#x9;c&#xA;&#x9;endif&#xA;)->union(&#xA;&#x9;Set{eContainer()}&#xA;)->select(oclIsKindOf(Block))->collect(&#xA;&#x9;oclAsType(Block)&#xA;)->asOrderedSet()"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This derived feature returns all blocks that surround this local variable declaration.&#xD;&#xA;This is a helper feature for ensuring that the names of local variables are unique."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedNamedElementExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="To perform an action on a value of a variable of a \rtsc we use the typed named element expression, which has a reference to a typed named element and optional indicies if a concrete array element should be referenced."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedNamedElement" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//behavior/TypedNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indices" upperBound="-1"
        eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indices which refer to an concrete index of an array."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayInitializeExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Used to initialize a typed named element of type ArrayDataType (or a subtype)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NondeterministicChoiceExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The nondeterministic choice expression selects a value from an interval of integers&#xD;&#xA;nondeterministically. It may be used to abstract from computations or interactions&#xD;&#xA;that will modify a value of a variable, but are not yet implementable, e.g., within&#xD;&#xA;a real-time coordination protocol. Nondeterministic choice expressions may only&#xD;&#xA;be used as right-hand side of an assignment."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/Range"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The range defines the lower bound and the upper bound of the interval from which&#xD;&#xA;values will be chosen nondeterministically. Every value in this interval will be&#xD;&#xA;chosen with the same probability."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//types/PrimitiveDataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The base type for the interval defined by the range. We only allow for integer types."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
