/**
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.muml.allocation.ilp.lpsolve.xtext.serializer;

import de.uni_paderborn.fujaba.muml.allocation.ilp.lpsolve.xtext.serializer.AbstractLPSolveSemanticSequencer;

@SuppressWarnings("all")
public class LPSolveSemanticSequencer extends AbstractLPSolveSemanticSequencer {
}
