/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.graphviz.dot.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DotLanguageStandaloneSetup extends DotLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new DotLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

