/**
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.graphviz.plain.xtext.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class GraphvizPlainProposalProvider extends AbstractGraphvizPlainProposalProvider {
}
