/**
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.ui;

import de.fraunhofer.iem.ui.AbstractProjectPlanningUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ProjectPlanningUiModule extends AbstractProjectPlanningUiModule {
  public ProjectPlanningUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
