/*
 * generated by Xtext
 */
package org.muml.psm.allocation.language.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.muml.psm.allocation.language.xtext.ui.internal.AllocationSpecificationLanguageActivator;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AllocationSpecificationLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AllocationSpecificationLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AllocationSpecificationLanguageActivator.getInstance().getInjector(AllocationSpecificationLanguageActivator.DE_UNI_PADERBORN_FUJABA_MUML_ALLOCATION_LANGUAGE_ALLOCATIONSPECIFICATIONLANGUAGE);
	}
	
}
