/*
 * generated by Xtext
 */
package org.muml.storydiagram.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PathExpressionsUiModule extends org.muml.storydiagram.expressions.ui.AbstractPathExpressionsUiModule {
	public PathExpressionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
