/**
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.projectPlanning;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Employee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.iem.projectPlanning.Employee#getName <em>Name</em>}</li>
 *   <li>{@link de.fraunhofer.iem.projectPlanning.Employee#getHasResource <em>Has Resource</em>}</li>
 *   <li>{@link de.fraunhofer.iem.projectPlanning.Employee#getHasCapabilities <em>Has Capabilities</em>}</li>
 *   <li>{@link de.fraunhofer.iem.projectPlanning.Employee#getRatings <em>Ratings</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.iem.projectPlanning.ProjectPlanningPackage#getEmployee()
 * @model
 * @generated
 */
public interface Employee extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.fraunhofer.iem.projectPlanning.ProjectPlanningPackage#getEmployee_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.fraunhofer.iem.projectPlanning.Employee#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Has Resource</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Resource</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Resource</em>' attribute.
   * @see #setHasResource(int)
   * @see de.fraunhofer.iem.projectPlanning.ProjectPlanningPackage#getEmployee_HasResource()
   * @model
   * @generated
   */
  int getHasResource();

  /**
   * Sets the value of the '{@link de.fraunhofer.iem.projectPlanning.Employee#getHasResource <em>Has Resource</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Resource</em>' attribute.
   * @see #getHasResource()
   * @generated
   */
  void setHasResource(int value);

  /**
   * Returns the value of the '<em><b>Has Capabilities</b></em>' reference list.
   * The list contents are of type {@link de.fraunhofer.iem.projectPlanning.Capability}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has Capabilities</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Capabilities</em>' reference list.
   * @see de.fraunhofer.iem.projectPlanning.ProjectPlanningPackage#getEmployee_HasCapabilities()
   * @model
   * @generated
   */
  EList<Capability> getHasCapabilities();

  /**
   * Returns the value of the '<em><b>Ratings</b></em>' containment reference list.
   * The list contents are of type {@link de.fraunhofer.iem.projectPlanning.Rating}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ratings</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ratings</em>' containment reference list.
   * @see de.fraunhofer.iem.projectPlanning.ProjectPlanningPackage#getEmployee_Ratings()
   * @model containment="true"
   * @generated
   */
  EList<Rating> getRatings();

} // Employee
