/*
 * generated by Xtext
 */
package de.uni_paderborn.uppaal.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractUppaalXMLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/0.4.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/templates/0.4.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/parsable/templates_parsable/0.4.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/visuals/0.4.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/declarations/0.4.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/declarations/system"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/expressions/0.4.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/types/0.4.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/declarations/global"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uni-paderborn.de/uppaal/statements/0.4.0"));
		return result;
	}
}
