<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentsdd" nsURI="http://www.fujaba.de/muml/verification/sdd/componentsdd/0.4.0"
    nsPrefix="componentsdd">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentStoryDecisionDiagram" eSuperTypes="../../de.uni_paderborn.fujaba.muml.verification.sdd/model/sdd.ecore#//AbstractStoryDecisionDiagram ../../de.uni_paderborn.fujaba.muml.reconfiguration/model/MumlReconfiguration.ecore#//StructuralCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentStoryPatternNode" eSuperTypes="../../de.uni_paderborn.fujaba.muml.verification.sdd/model/sdd.ecore#//PatternNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.componentstorypattern/model/ComponentStoryPattern.ecore#//ComponentStoryPattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluateComponentSDDExpression" eSuperTypes="../../de.uni_paderborn.fujaba.muml.componentstorypattern/model/ComponentStoryPattern.ecore#//TriggerEmbeddedComponentExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSDD" lowerBound="1"
        eType="#//ComponentStoryDecisionDiagram"/>
  </eClassifiers>
</ecore:EPackage>
