<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="actionLanguage"
    nsURI="http://www.fujaba.de/muml/actionlanguage/0.2.0" nsPrefix="actionLanguage">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The base package for all expressions which can be used for modeling actions, guards, invariants... . "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicOperator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the operators for binary logic expressions. The unary logic expression representing negated expressions is reflected by the NotExpression."/>
    </eAnnotations>
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="XOR" value="2"/>
    <eLiterals name="IMPLY" value="3"/>
    <eLiterals name="EQUIVALENT" value="4"/>
    <eLiterals name="AND_AND" value="5" literal="AND_AND"/>
    <eLiterals name="OR_OR" value="6" literal="OR_OR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparingOperator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the operators for comparing expressions."/>
    </eAnnotations>
    <eLiterals name="LESS"/>
    <eLiterals name="LESS_OR_EQUAL" value="1"/>
    <eLiterals name="EQUAL" value="2"/>
    <eLiterals name="GREATER_OR_EQUAL" value="3"/>
    <eLiterals name="GREATER" value="4"/>
    <eLiterals name="UNEQUAL" value="5"/>
    <eLiterals name="REGULAR_EXPRESSION" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For comparison of a String with a regular expression."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the operators for arithmetic expressions."/>
    </eAnnotations>
    <eLiterals name="PLUS"/>
    <eLiterals name="MINUS" value="1"/>
    <eLiterals name="TIMES" value="2"/>
    <eLiterals name="DIVIDE" value="3"/>
    <eLiterals name="MODULO" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextualExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents any expression in a textual language embedded into Story Diagrams, e.g. OCL or Java ."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionText" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Holds the expression, e.g. in OCL or Java."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="String representation of the used language which has to be unique. Examples are OCL and Java."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="String representation of the used language's version. The format is &lt;Major>.&lt;Minor>[.&lt;Revision>[.&lt;Build>]]&#xD;&#xA;Examples: 1.4 or 3.0.1 or 1.0.2.20101208."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents any literal, i.e. a value whose type is an EDataType. Literals are, for example, 5, 3.14, 'c', &quot;text&quot;, true."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="String representation of the value, e.g. &quot;5&quot;, &quot;3.14&quot;, &quot;c&quot;, &quot;text&quot;, or &quot;true&quot;."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a negated expression, e.g. NOT (a &lt; 5)."/>
      <contents xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents a negated expression, e.g. NOT (a &lt; 5)."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="unaryExpression" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
            containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Represents the operand of a NotExpression, e.g. a &lt; 5 in NOT (a &lt; 5)."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="unaryOperator" eType="#//UnaryOperator"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unaryExpression" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the operand of a NotExpression, e.g. a &lt; 5 in NOT (a &lt; 5)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unaryOperator" eType="#//UnaryOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents any binary expression like v &lt; 5 or x + 7."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the first operand of a binary expression, e.g. x in the expression x &lt; 5."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the second operand of a binary expression, e.g. 5 in the expression x &lt; 5."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="#//BinaryExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents comparing expressions like a &lt; 5 or a >= 7."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
        lowerBound="1" eType="#//ComparingOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies the expression's comparing operator, e.g. &lt;, >=, !=."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//BinaryExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents arithmetic expressions like a + 5 or a * 7."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
        lowerBound="1" eType="#//ArithmeticOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies the expression's arithmetic operator, e.g. +, -, *, /, or MODULO."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryLogicExpression" eSuperTypes="#//BinaryExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents binary, logic expressions like a AND b and a OR b."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
        lowerBound="1" eType="#//LogicOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies the expression's logic operator, e.g. AND, OR, or XOR."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssignOperator">
    <eLiterals name="UNSET" literal="UNSET"/>
    <eLiterals name="ASSIGN" value="1" literal=":="/>
    <eLiterals name="PLUS_EQUAL" value="2" literal="+="/>
    <eLiterals name="EQUAL_PLUS" value="3" literal="=+"/>
    <eLiterals name="MINUS_EQUAL" value="4" literal="-="/>
    <eLiterals name="EQUAL_MINUS" value="5" literal="=-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IncrementDecrementOperator">
    <eLiterals name="UNSET" literal="UNSET"/>
    <eLiterals name="INCREMENT" value="2" literal="++"/>
    <eLiterals name="DECREMENT" value="1" literal="--"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperator">
    <eLiterals name="LESS" literal="&lt;"/>
    <eLiterals name="LESS_OR_EQUAL" value="1" literal="&lt;="/>
    <eLiterals name="EQUAL" value="2" literal="=="/>
    <eLiterals name="GREATER_OR_EQUAL" value="3" literal=">="/>
    <eLiterals name="GREATER" value="4" literal=">"/>
    <eLiterals name="UNEQUAL" value="5" literal="&lt;>"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
    <eLiterals name="NOT" literal="not"/>
    <eLiterals name="MINUS" value="1" literal="-"/>
    <eLiterals name="PLUS" value="2" literal="+"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" abstract="true" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopTest" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileLoop" eSuperTypes="#//Loop"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoWhileLoop" eSuperTypes="#//Loop"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignOperator" eType="#//AssignOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignExpression" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incrementDecrementOperator"
        eType="#//IncrementDecrementOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/core/Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoop" eSuperTypes="#//Loop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initalizeExpression" eType="#//Assignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countingExpression" eType="#//Assignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifCondition" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifBlock" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfConditions" upperBound="-1"
        eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfBlocks" upperBound="-1"
        eType="#//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeExpression" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/core/Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationCall" eSuperTypes="../../org.storydriven.core/model/core.ecore#//expressions/Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/core/Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterBinding" upperBound="-1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/core/ParameterBinding"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValuesForBinding"
        upperBound="-1" eType="ecore:EClass ../../org.storydriven.core/model/core.ecore#//expressions/Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
