/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.graphviz.dot.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DotLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.uni_paderborn.fujaba.graphviz.dot.xtext.ui.internal.DotLanguageActivator.getInstance().getInjector("de.uni_paderborn.fujaba.graphviz.dot.xtext.DotLanguage");
	}
	
}
