/**
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.graphviz.dot.xtext.validation;

import de.uni_paderborn.fujaba.graphviz.dot.xtext.validation.AbstractDotLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DotLanguageValidator extends AbstractDotLanguageValidator {
}
