/*
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.muml.allocation.ilp.lpsolve.xtext.ui.contentassist

import de.uni_paderborn.fujaba.muml.allocation.ilp.lpsolve.xtext.ui.contentassist.AbstractLPSolveProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LPSolveProposalProvider extends AbstractLPSolveProposalProvider {
}
