version: "3"

services:
  broker-web:
    image: hub.cs.upb.de/productionbroker/broker-web:development
    container_name: broker-web
    environment:
      VIRTUAL_HOST: virtual-factory-iem-fraunhofer.cs.upb.de
    volumes:
      - ./config/config.js:/opt/productionbroker/server/config.js
    networks:
      - production    

  broker-db-service:
    image: hub.cs.upb.de/productionbroker/broker-db-service:latest
    restart: always
    container_name: broker-db-service
    volumes:
      - ./broker-db-service:/opt/pbdb/config
    networks:
      - production
    
  broker-db:
    image: mongo
    container_name: broker-db
    networks:
      - production

  broker-integration-test:
    image: broker
    build: 
        context: org.muml.example.productionBroker/src-gen-container/broker/operations/
        dockerfile: Dockerfile-integration-test
    container_name: broker
    links:
      - broker-web
    environment:
      WEB_HOST: broker-db-service
      WEB_PORT: 3000
    volumes:
      - ./db/broker.db:/opt/app/broker.db:rw
    networks:
      - production


volumes:
  dbvolume:

networks:
  production:
