<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://www.muml.org/core/1.0.0" nsPrefix="core">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The core package is the root package for the storydriven core meta-model. It defines several abstract super classes which implement an extension mechanism as well as recurring structural features like, e.g., names of elements. The classes in this package are intended to be sub-classed by any meta-model element."/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true"
      eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for all meta-model elements that may carry a comment in form of a string."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;no comment provided&quot;">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The comment string that can be used to attach arbitrary information to CommentableElements."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendableElement" abstract="true" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for the whole story diagram model. The ExtendableElement specifies the extension mechanism that can be used to extend an object by an Extension containing additional attributes and references."/>
    </eAnnotations>
    <eOperations name="getExtension" lowerBound="1" eType="#//Extension">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;Extension> extensions = this.getExtensions();&#xA;&#x9;&#x9;&#x9;&#x9;for (Extension extension : extensions) {&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;if (type.isInstance(extension)) {&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;return extension;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;&#x9;return null;"/>
      </eAnnotations>
      <eParameters name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" ordered="false"
        upperBound="-1" eType="#//Extension" containment="true" eOpposite="#//Extension/extendableBase">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Extendable Elements can be extended by an Extension."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extension" abstract="true" eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for an Extension that can be defined for an object."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendableBase" ordered="false"
        eType="#//ExtendableElement" eOpposite="#//ExtendableElement/extensions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The extendable element that is extended by this extension."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for all meta-model elements that carry a name. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name attribute of a meta-model element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for all meta-model elements that are typed by means of an EClassifier or an EGenericType."/>
    </eAnnotations>
    <eOperations name="setClassifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EGenericType genericType = getGenericType();&#xA;if (genericType == null) {&#xA;&#x9;genericType = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEGenericType();&#xA;&#x9;setGenericType(genericType);&#xA;}&#xA;genericType.setEClassifier(classifier);"/>
      </eAnnotations>
      <eParameters name="classifier" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericType" ordered="false"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"
        unsettable="true" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The EMF EGenericType that is used to type this typed element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false"
        lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The type of this ObjectVariable, given as an EClass."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if (self.genericType &lt;> null) then self.genericType.eClassifier else null endif"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" abstract="true" eSuperTypes="#//NamedElement #//CommentableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Repositories are used for grouping model elements that may be reused in different contexts."/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="expressions" nsURI="http://www.muml.org/core/expressions/1.0.0"
      nsPrefix="expressions">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The base package for all expressions that can be used for modeling activities and patterns."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents any expression in an embedded textual language, e.g. OCL or Java. An expression's type is dynamically derived by an external mechanism (see TypedElement)."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextualExpression" eSuperTypes="#//expressions/Expression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents any expression in a textual language embedded into Story Diagrams, e.g. OCL or Java ."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionText" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Holds the expression, e.g. in OCL or Java."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String representation of the used language which has to be unique. Examples are OCL and Java."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String representation of the used language's version. The format is &lt;Major>.&lt;Minor>[.&lt;Revision>[.&lt;Build>]]&#xD;&#xA;Examples: 1.4 or 3.0.1 or 1.0.2.20101208."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eSubpackages name="common" nsURI="http://www.muml.org/core/expressions/common/1.0.0"
        nsPrefix="common">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
        <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
        <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The package for all common expressions that can be used for modeling activities and patterns."/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EEnum" name="LogicOperator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Defines the operators for binary logic expressions."/>
        </eAnnotations>
        <eLiterals name="AND"/>
        <eLiterals name="OR" value="1"/>
        <eLiterals name="XOR" value="2"/>
        <eLiterals name="IMPLY" value="3"/>
        <eLiterals name="EQUIVALENT" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ComparingOperator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Defines the operators for comparing expressions. The operators LESS, LESS_OR_EQUAL, EQUAL,&#xD;&#xA;GREATER_OR_EQUAL, GREATER, and UNEQUAL have their usual semantics.&#xD;&#xA;The operator REGULAR_EXPRESSION enables to compare a String contained in the&#xD;&#xA;left hand side of a ComparisonExpression with a regular expression contained in the &#xD;&#xA;right hand side of the ComparisonExpression."/>
        </eAnnotations>
        <eLiterals name="LESS"/>
        <eLiterals name="LESS_OR_EQUAL" value="1"/>
        <eLiterals name="EQUAL" value="2"/>
        <eLiterals name="GREATER_OR_EQUAL" value="3"/>
        <eLiterals name="GREATER" value="4"/>
        <eLiterals name="UNEQUAL" value="5"/>
        <eLiterals name="REGULAR_EXPRESSION" value="6">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="For comparison of a String with a regular expression."/>
          </eAnnotations>
        </eLiterals>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Defines the operators for arithmetic expressions."/>
        </eAnnotations>
        <eLiterals name="PLUS"/>
        <eLiterals name="MINUS" value="1"/>
        <eLiterals name="TIMES" value="2"/>
        <eLiterals name="DIVIDE" value="3"/>
        <eLiterals name="MODULO" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The operator type used to specify unary logic expressions."/>
        </eAnnotations>
        <eLiterals name="NOT"/>
        <eLiterals name="MINUS" value="2"/>
        <eLiterals name="INCREMENT" value="3"/>
        <eLiterals name="DECREMENT" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents an unary expression."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="enclosedExpression"
            ordered="false" lowerBound="1" eType="#//expressions/Expression" containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Represents the operand of a NotExpression, e.g. a &lt; 5 in NOT (a &lt; 5)."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
            eType="#//expressions/common/UnaryOperator">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Represents the operator of the expression."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true"
          eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents any binary expression like v &lt; 5 or x + 7."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" ordered="false"
            lowerBound="1" eType="#//expressions/Expression" containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Represents the first operand of a binary expression, e.g. x in the expression x &lt; 5."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" ordered="false"
            lowerBound="1" eType="#//expressions/Expression" containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Represents the second operand of a binary expression, e.g. 5 in the expression x &lt; 5."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="#//expressions/common/BinaryExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents comparing expressions like a &lt; 5 or a >= 7."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
            lowerBound="1" eType="#//expressions/common/ComparingOperator">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the expression's comparing operator, e.g. &lt;, >=, !=."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//expressions/common/BinaryExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents arithmetic expressions like a + 5 or a * 7."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
            lowerBound="1" eType="#//expressions/common/ArithmeticOperator">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the expression's arithmetic operator, e.g. +, -, *, /, or MODULO."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LogicalExpression" eSuperTypes="#//expressions/common/BinaryExpression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents binary, logic expressions like a AND b and a OR b."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
            lowerBound="1" eType="#//expressions/common/LogicOperator">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the expression's logic operator, e.g. AND, OR, or XOR."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents any literal, i.e. a value whose type is an EDataType. Literals are, for example, 5, 3.14, 'c', &quot;text&quot;, true."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="String representation of the value, e.g. &quot;5&quot;, &quot;3.14&quot;, &quot;c&quot;, &quot;text&quot;, or &quot;true&quot;."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="modelinstance" nsURI="http://www.muml.org/modelinstance/1.0.0"
      nsPrefix="modelinstance">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The package modelinstance defines the base classes for the FUJABA xmi format.&#xD;&#xA;In detail, it defines a root node and model element categories in order to serialize&#xD;&#xA;the model elements that may be contained in a FUJABA model."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="RootNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The RootNode is the single root element of the XMI file which is generated for&#xD;&#xA;the FUJABA model."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
          eType="#//modelinstance/ModelElementCategory" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The model element categories which are contained in this RootNode."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElementCategory">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="ExclusivelyContainsValidElements"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="ExclusivelyContainsValidElements" value="self.modelElements->select (e | not isValidElement(e))->isEmpty()"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ModelElementCategory contains all model elements of a FUJABA model that&#xD;&#xA;have the same type and will be opened by the same editor. A ModelElementCategory&#xD;&#xA;may only store subclasses of NamedElement."/>
      </eAnnotations>
      <eOperations name="isValidElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Evaluates for the passed object whether it is a valid model element for this &#xD;&#xA;ModelElementCategory."/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="body" value="isValidEClass(object.oclAsType(ecore::EObject).eClass())"/>
        </eAnnotations>
        <eParameters name="object" eType="#//ExtendableElement">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The passed object that we check whether it is a valid model element for this &#xD;&#xA;ModelElementCategory."/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="isValidEClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Evaluates for the passed ecore class whether it is a valid type for model element for this ModelElementCategory."/>
          <details key="body" value="ModelInstancePlugin plugin = ModelInstancePlugin.getInstance();&#xD;&#xA;if (plugin != null) {&#xD;&#xA;&#x9;ModelElementCategoryRegistry registry = plugin.getModelElementCategoryRegistry();&#xD;&#xA;&#x9;return registry.isValidEClass(key, eClass);&#xD;&#xA;}&#xD;&#xA;return false;"/>
        </eAnnotations>
        <eParameters name="eClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The passed eClass that we check whether it is a valid type for model element for this ModelElementCategory."/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
          eType="#//ExtendableElement" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The ModelElements which are contained in this category. All model elements&#xD;&#xA;must be of the same type."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The uniquely identifying key of this category. The key of the category may be&#xD;&#xA;used by editors to register for the model elements contained in this section."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A human readable name for this category."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
