/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.graphviz.plain.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GraphvizPlainUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.uni_paderborn.fujaba.graphviz.plain.xtext.ui.internal.GraphvizPlainActivator.getInstance().getInjector("de.uni_paderborn.fujaba.graphviz.plain.xtext.GraphvizPlain");
	}
	
}
