/**
 *
 * $Id$
 */
package de.uni_paderborn.uppaal.declarations.validation;

import de.uni_paderborn.uppaal.declarations.Initializer;

import de.uni_paderborn.uppaal.expressions.Expression;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_paderborn.uppaal.declarations.Variable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableValidator {
	boolean validate();

	boolean validateIndex(EList<Expression> value);
	boolean validateInitializer(Initializer value);
}
