/**
 * generated by Xtext
 */
package org.muml.psm.allocation.language.xtext.serializer;

import org.muml.psm.allocation.language.xtext.serializer.AbstractAllocationSpecificationLanguageSemanticSequencer;

@SuppressWarnings("all")
public class AllocationSpecificationLanguageSemanticSequencer extends AbstractAllocationSpecificationLanguageSemanticSequencer {
}
