/*
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.ui;

import com.google.inject.Injector;
import de.fraunhofer.iem.projectPlanning.ui.internal.ProjectPlanningActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProjectPlanningExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProjectPlanningActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProjectPlanningActivator.getInstance().getInjector(ProjectPlanningActivator.DE_FRAUNHOFER_IEM_PROJECTPLANNING);
	}
	
}
