<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IEC61131" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0"
    nsPrefix="IEC61131">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="main package for iec 61131 meta model divided in three main packages: common elements between all defined languages (core), language extensions (languages) and extensions for already compiled program fragments"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IEC61131">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="toplevel class for an iec 61131 model instance containing library elements and configuration elements"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraryDeclarations" upperBound="-1"
        eType="#//core/LibraryElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraryReferences" upperBound="-1"
        eType="#//core/LibraryElementReference" containment="true"/>
  </eClassifiers>
  <eSubpackages name="core" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core"
      nsPrefix="core">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="this package contains all common elements of iec 61131's languages"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="LibraryElement" abstract="true" eSuperTypes="#//core/literals/NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains all library elements such as pou's, configurations and types"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LibraryElementReference" abstract="true"/>
    <eSubpackages name="types" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core/types"
        nsPrefix="types">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains standard types included in iec 61131. additionally individual defined data types called derived data types"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="ElementaryType" abstract="true"
          interface="true" eSuperTypes="#//core/types/SimpleSpecification #//core/types/NonGenericType #//core/pous/FunctionReturnDomain"/>
      <eClassifiers xsi:type="ecore:EClass" name="NumericType" abstract="true" interface="true"
          eSuperTypes="#//core/types/ElementaryType"/>
      <eClassifiers xsi:type="ecore:EClass" name="DateType" eSuperTypes="#//core/types/ElementaryType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#//core/types/EDateType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BitStringType" eSuperTypes="#//core/types/ElementaryType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#//core/types/EBitStringType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TimeType" eSuperTypes="#//core/types/ElementaryType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//core/types/ETimeType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IntegerType" abstract="true" interface="true"
          eSuperTypes="#//core/types/NumericType"/>
      <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="#//core/types/NumericType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#//core/types/ERealType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SignedIntegerType" eSuperTypes="#//core/types/IntegerType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#//core/types/ESignedIntegerType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UnsignedIntegerType" eSuperTypes="#//core/types/IntegerType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#//core/types/EUnsignedIntegerType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="EDateType">
        <eLiterals name="DATE"/>
        <eLiterals name="TIMEOFDAY" value="1"/>
        <eLiterals name="TOD" value="2"/>
        <eLiterals name="DATEANDTIME" value="3"/>
        <eLiterals name="DT" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ElementaryStringType" eSuperTypes="#//core/types/ElementaryType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#//core/types/EElementaryStringType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="EElementaryStringType">
        <eLiterals name="STRING"/>
        <eLiterals name="WSTRING" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="EBitStringType">
        <eLiterals name="BOOL"/>
        <eLiterals name="DWORD" value="1"/>
        <eLiterals name="LWORD" value="2"/>
        <eLiterals name="WORD" value="3"/>
        <eLiterals name="BYTE" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ESignedIntegerType">
        <eLiterals name="SINT"/>
        <eLiterals name="INT" value="1"/>
        <eLiterals name="LINT" value="2"/>
        <eLiterals name="DINT" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="EUnsignedIntegerType">
        <eLiterals name="USINT"/>
        <eLiterals name="UINT" value="1"/>
        <eLiterals name="UDINT" value="2"/>
        <eLiterals name="ULINT" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ERealType">
        <eLiterals name="REAL"/>
        <eLiterals name="LREAL" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataTypeDeclaration" abstract="true"
          eSuperTypes="#//core/LibraryElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="SingleElementTypeDeclaration" abstract="true"
          eSuperTypes="#//core/types/DataTypeDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeDeclaration" eSuperTypes="#//core/types/DataTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/types/ArraySpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StructureTypeDeclaration" eSuperTypes="#//core/types/DataTypeDeclaration #//core/declarations/VarSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
            eType="#//core/types/StructureSpecification" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringTypeDeclaration" eSuperTypes="#//core/types/DataTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
            eType="#//core/literals/IntegerLiteral" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//core/literals/CharacterString"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
            eType="#//core/types/ElementaryStringType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleTypeDeclaration" eSuperTypes="#//core/types/SingleElementTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/types/SimpleSpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SubrangeTypeDeclaration" eSuperTypes="#//core/types/SingleElementTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/types/SubrangeSpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedTypeDeclaration" eSuperTypes="#//core/types/SingleElementTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/types/EnumeratedSpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleSpecInit" eSuperTypes="#//core/types/StructureElementDomain #//core/declarations/InstanceSpecificSpecInit #//core/declarations/Var1SpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
            eType="#//core/types/SimpleSpecification" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//core/literals/Constant"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleSpecification" abstract="true"
          eSuperTypes="#//core/declarations/SharedVarSpec #//core/declarations/Var1Specification"/>
      <eClassifiers xsi:type="ecore:EClass" name="SubrangeSpecInit" eSuperTypes="#//core/types/StructureElementDomain #//core/declarations/InstanceSpecificSpecInit #//core/declarations/Var1SpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//core/literals/SignedInteger"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
            eType="#//core/types/SubrangeSpecification" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Subrange">
        <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" lowerBound="1"
            eType="#//core/literals/SignedInteger" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" lowerBound="1"
            eType="#//core/literals/SignedInteger" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SubrangeSpecification" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/SharedVarSpec #//core/declarations/Var1Specification"/>
      <eClassifiers xsi:type="ecore:EClass" name="SubrangeTypeSpecification" eSuperTypes="#//core/types/SubrangeSpecification #//languages/st/CaseListElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="integerType" lowerBound="1"
            eType="#//core/types/IntegerType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1"
            eType="#//core/types/Subrange" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedSpecInit" eSuperTypes="#//core/types/StructureElementDomain #//core/declarations/InstanceSpecificSpecInit #//core/declarations/Var1SpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
            eType="#//core/types/EnumeratedSpecification" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initialization" eType="#//core/types/EnumeratedValue"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedSpecification" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/SharedVarSpec #//core/declarations/Var1Specification"/>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedValue" eSuperTypes="#//core/literals/NamedElement #//core/types/StructureElementValue #//core/configurations/ProgDataSource #//languages/st/CaseListElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//core/types/EnumeratedTypeDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedTypeSpecification" eSuperTypes="#//core/types/EnumeratedSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueList" lowerBound="1"
            upperBound="-1" eType="#//core/types/EnumeratedValue" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArraySpecInit" eSuperTypes="#//core/types/StructureElementDomain #//core/declarations/InstanceSpecificSpecInit #//core/declarations/Var2SpecInit #//core/declarations/LocatedVarSpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
            eType="#//core/types/ArraySpecification" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initialization" eType="#//core/types/ArrayInit"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArraySpecification" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/ArrayStructVarSpec #//core/declarations/SharedVarSpec"/>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayInit" eSuperTypes="#//core/types/ArrayInitElement #//core/types/StructureElementValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="initElements" lowerBound="1"
            upperBound="-1" eType="#//core/types/ArrayInitElement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeSpecification" eSuperTypes="#//core/types/ArraySpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="ranges" lowerBound="1"
            upperBound="-1" eType="#//core/types/Subrange" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="ofType" lowerBound="1"
            eType="#//core/types/NonGenericType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayInitElement" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="StructureSpecification" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="StructureDeclaration" eSuperTypes="#//core/types/StructureSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declElements" lowerBound="1"
            upperBound="-1" eType="#//core/types/StructureElementDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InitializedStructure" eSuperTypes="#//core/types/StructureSpecification #//core/types/StructureElementDomain #//core/declarations/InstanceSpecificSpecInit #//core/declarations/Var2SpecInit #//core/declarations/LocatedVarSpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="definedStructure" lowerBound="1"
            eType="#//core/types/StructureTypeDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//core/types/StructureInit"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StructureElementDeclaration" eSuperTypes="#//core/literals/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
            eType="#//core/types/StructureElementDomain" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StructureInit" eSuperTypes="#//core/types/StructureElementValue #//core/types/ArrayInitElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="elementInit" lowerBound="1"
            upperBound="-1" eType="#//core/types/StructureElementInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StructureElementDomain" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="StructureElementInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
            eType="#//core/types/StructureElementDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            eType="#//core/types/StructureElementValue" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StructureElementValue" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" interface="true"
          eSuperTypes="#//core/LibraryElementReference"/>
      <eClassifiers xsi:type="ecore:EClass" name="NonGenericType" abstract="true"
          interface="true" eSuperTypes="#//core/types/DataType"/>
      <eClassifiers xsi:type="ecore:EClass" name="GenericType" eSuperTypes="#//core/types/DataType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#//core/types/EGenericType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="EGenericType">
        <eLiterals name="ANY"/>
        <eLiterals name="ANY_DERIVED" value="1"/>
        <eLiterals name="ANY_ELEMENTARY" value="2"/>
        <eLiterals name="ANY_MAGNITUDE" value="3"/>
        <eLiterals name="ANY_NUM" value="4"/>
        <eLiterals name="ANY_REAL" value="5"/>
        <eLiterals name="ANY_INT" value="6"/>
        <eLiterals name="ANY_BIT" value="7"/>
        <eLiterals name="ANY_STRING" value="8"/>
        <eLiterals name="ANY_DATE" value="9"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ETimeType">
        <eLiterals name="TIME"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayTypeReference" eSuperTypes="#//core/types/ArraySpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="arrayType" lowerBound="1"
            eType="#//core/types/ArrayTypeDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleTypeReference" eSuperTypes="#//core/types/SimpleSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="simpleType" lowerBound="1"
            eType="#//core/types/SimpleTypeDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SubrangeTypeReference" eSuperTypes="#//core/types/SubrangeSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="subrangeType" lowerBound="1"
            eType="#//core/types/SubrangeTypeDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedTypeReference" eSuperTypes="#//core/types/EnumeratedSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="enumeratedType" lowerBound="1"
            eType="#//core/types/EnumeratedTypeDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StructurePointer" eSuperTypes="#//core/declarations/SharedVarSpec #//core/declarations/ArrayStructVarSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="structureType" lowerBound="1"
            eType="#//core/types/StructureTypeDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedValuePointer" eSuperTypes="#//core/types/ArrayInitElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="enumValue" lowerBound="1"
            eType="#//core/types/EnumeratedValue"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HardwareResourceTypeName" eSuperTypes="#//core/LibraryElementReference #//core/literals/NamedElement"/>
    </eSubpackages>
    <eSubpackages name="operators" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core/operators"
        nsPrefix="operators"/>
    <eSubpackages name="literals" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core/literals"
        nsPrefix="literals">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains literals of iec 61131, identifer is defined here"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//core/literals/Literal #//core/types/ArrayInitElement #//core/types/StructureElementValue #//core/configurations/DataSource #//core/configurations/ProgDataSource #//languages/st/PrimaryExpressionValue"/>
      <eClassifiers xsi:type="ecore:EClass" name="NumericLiteral" eSuperTypes="#//core/literals/Constant"/>
      <eClassifiers xsi:type="ecore:EClass" name="CharacterLiteral" eSuperTypes="#//core/literals/Constant"/>
      <eClassifiers xsi:type="ecore:EClass" name="BitStringLiteral" eSuperTypes="#//core/literals/Constant">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeName" eType="#//core/types/BitStringType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Literal">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//core/literals/Constant">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" abstract="true"
          eSuperTypes="#//core/literals/NumericLiteral">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeName" eType="#//core/types/IntegerType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RealLiteral" eSuperTypes="#//core/literals/NumericLiteral">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeName" eType="#//core/types/RealType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SignedInteger" eSuperTypes="#//languages/st/CaseListElement #//core/literals/IntegerLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="BinaryInteger" eSuperTypes="#//core/literals/IntegerLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="OctalInteger" eSuperTypes="#//core/literals/IntegerLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="HexInteger" eSuperTypes="#//core/literals/IntegerLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="UnsignedInteger" eSuperTypes="#//core/literals/IntegerLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="CharacterString" eSuperTypes="#//core/literals/Literal"/>
      <eClassifiers xsi:type="ecore:EClass" name="SingleByteCharacterString" eSuperTypes="#//core/literals/CharacterString"/>
      <eClassifiers xsi:type="ecore:EClass" name="DoubleByteCharacterString" eSuperTypes="#//core/literals/CharacterString"/>
      <eClassifiers xsi:type="ecore:EClass" name="TimeLiteral" eSuperTypes="#//core/literals/Literal #//core/literals/Constant"/>
      <eClassifiers xsi:type="ecore:EClass" name="Duration" eSuperTypes="#//core/literals/TimeLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="TimeOfDay" eSuperTypes="#//core/literals/TimeLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//core/literals/TimeLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="DateAndTime" eSuperTypes="#//core/literals/TimeLiteral"/>
      <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="variables" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core/variables"
        nsPrefix="variables">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains 3 different kinds of variables"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="SymbolicVariable" abstract="true"
          eSuperTypes="#//core/variables/NonGlobalVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="DirectVariable" eSuperTypes="#//core/variables/NonGlobalVariable #//core/configurations/DataSource #//core/configurations/DataSink #//core/configurations/ProgDataSource #//core/declarations/AccessDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            upperBound="-1" eType="#//core/literals/IntegerLiteral" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="LocationPrefix">
        <eLiterals name="I"/>
        <eLiterals name="Q" value="1"/>
        <eLiterals name="M" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SizePrefix">
        <eLiterals name="X"/>
        <eLiterals name="B" value="1"/>
        <eLiterals name="W" value="2"/>
        <eLiterals name="D" value="3"/>
        <eLiterals name="L" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NamedVariable" eSuperTypes="#//core/variables/SymbolicVariable #//core/literals/NamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="MultiElementVariable" abstract="true"
          eSuperTypes="#//core/variables/SymbolicVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="StructuredVariable" eSuperTypes="#//core/variables/MultiElementVariable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="recordVariable" lowerBound="1"
            eType="#//core/variables/SymbolicVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fieldSelector" lowerBound="1"
            eType="#//core/variables/FieldSelector" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayVariable" eSuperTypes="#//core/variables/MultiElementVariable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="subscriptedVariable"
            lowerBound="1" eType="#//core/variables/SymbolicVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="subscript" lowerBound="1"
            upperBound="-1" eType="#//languages/st/Expression"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FieldSelector" eSuperTypes="#//core/literals/NamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalVar" eSuperTypes="#//core/variables/Variable #//core/literals/NamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="NonGlobalVariable" abstract="true"
          interface="true" eSuperTypes="#//core/variables/Variable"/>
      <eClassifiers xsi:type="ecore:EClass" name="FBName" eSuperTypes="#//core/variables/Variable #//core/literals/NamedElement"/>
    </eSubpackages>
    <eSubpackages name="declarations" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core/declarations"
        nsPrefix="declarations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains all kinds of variable declarations, different types of variables are supported by this model"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="IOVarDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/FunctionVariableDeclaration #//core/declarations/FunctionBlockVariableDeclaration #//core/declarations/ProgramVariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="InputVarContainer" eSuperTypes="#//core/declarations/IOVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="retain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/InputDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OutputVarContainer" eSuperTypes="#//core/declarations/IOVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/VarInitDeclaration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="retain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InputOutputVarContainer" eSuperTypes="#//core/declarations/IOVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/VarDeclarationOnly" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FBProgramVarDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/FunctionBlockVariableDeclaration #//core/declarations/ProgramVariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="VarDeclarationContainer" eSuperTypes="#//core/declarations/FBProgramVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="declarationType" eType="#//core/declarations/VarDeclarationType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/VarInitDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="VarDeclarationType">
        <eLiterals name="NIL"/>
        <eLiterals name="RETAIN" value="1"/>
        <eLiterals name="NONRETAIN" value="2"/>
        <eLiterals name="CONSTANT" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExternalVarContainer" eSuperTypes="#//core/declarations/FBProgramVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/ExternalVarDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TempVarDeclarationContainer" eSuperTypes="#//core/declarations/FBProgramVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/TempVarDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IncomplLocatedVarContainer" eSuperTypes="#//core/declarations/FBProgramVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="retain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/IncomplLocatedVarDeclaration"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgramSpecificDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/ProgramVariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="LocatedVarDeclarationContainer"
          eSuperTypes="#//core/declarations/ProgramSpecificDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//core/declarations/VarDeclarationType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/LocatedVarDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgramAccessContainer" eSuperTypes="#//core/declarations/ProgramSpecificDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/ProgramAccessDeclaration"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionVarContainer" eSuperTypes="#//core/declarations/FunctionVariableDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/Var2SpecInitDecl" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="CONSTANT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalVarDeclarationContainer" eSuperTypes="#//core/declarations/ConfigurationVariableDeclaration #//core/declarations/ResourceVariableDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/GlobalVarDeclaration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="globalAttribute" eType="#//core/declarations/GlobalAttribute"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionVariableDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/VariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockVariableDeclaration"
          abstract="true" interface="true" eSuperTypes="#//core/declarations/ProgramVariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="ProgramVariableDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/VariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="ConfigurationVariableDeclaration"
          abstract="true" interface="true" eSuperTypes="#//core/declarations/VariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="ResourceVariableDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/VariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="AccessVarContainer" eSuperTypes="#//core/declarations/ConfigurationSpecificDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/AccessDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceSpecificVarContainter" eSuperTypes="#//core/declarations/ConfigurationSpecificDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" lowerBound="1"
            upperBound="-1" eType="#//core/declarations/InstanceSpecificVarInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConfigurationSpecificDeclaration"
          abstract="true" interface="true" eSuperTypes="#//core/declarations/ConfigurationVariableDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="InputDeclaration" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="EdgeDeclaration" eSuperTypes="#//core/declarations/InputDeclaration #//core/declarations/NamedVariableDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeType" lowerBound="1"
            eType="#//core/declarations/EdgeType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="EdgeType">
        <eLiterals name="R_EDGE"/>
        <eLiterals name="F_EDGE" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="VarInitDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/InputDeclaration"/>
      <eClassifiers xsi:type="ecore:EClass" name="Var1SpecInitDecl" eSuperTypes="#//core/declarations/NamedVariableDeclaration #//core/declarations/LocatedVarSpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/declarations/Var1SpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringVarDecl" abstract="true" eSuperTypes="#//core/declarations/TempVarDeclaration #//core/declarations/Var2SpecInit"/>
      <eClassifiers xsi:type="ecore:EClass" name="SingleByteStringSpecInit" eSuperTypes="#//core/declarations/SingleByteStringVar #//core/declarations/StringVarDecl #//core/declarations/LocatedVarSpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//core/literals/SingleByteCharacterString"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DoubleByteStringSpecInit" eSuperTypes="#//core/declarations/StringVarDecl #//core/declarations/DoubleByteStringVar #//core/declarations/LocatedVarSpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//core/literals/DoubleByteCharacterString"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="VarDeclarationOnly" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="TempVarDeclaration" abstract="true"
          interface="true" eSuperTypes="#//core/declarations/VarDeclarationOnly"/>
      <eClassifiers xsi:type="ecore:EClass" name="Var1Decl" abstract="true" eSuperTypes="#//core/declarations/TempVarDeclaration #//core/declarations/NamedVariableDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
            eType="#//core/declarations/Var1Specification" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LocatedVarDeclaration" eSuperTypes="#//core/declarations/NamedVariableDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
            eType="#//core/variables/DirectVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/declarations/LocatedVarSpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IncomplLocatedVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//core/variables/LocationPrefix"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" lowerBound="1"
            eType="#//core/variables/NamedVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="spec" lowerBound="1"
            eType="#//core/declarations/VarSpec" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringSpecification" abstract="true"
          eSuperTypes="#//core/declarations/VarSpec #//core/declarations/InstanceSpecificSpecInit"/>
      <eClassifiers xsi:type="ecore:EClass" name="VarSpec" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="OnlyNamedGlobalVar" eSuperTypes="#//core/declarations/GlobalVarSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" lowerBound="1"
            eType="#//core/variables/GlobalVar" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LocatedGlobalVar" eSuperTypes="#//core/declarations/GlobalVarSpec">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" eType="#//core/variables/GlobalVar"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
            eType="#//core/variables/DirectVariable" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalVarSpec" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EEnum" name="GlobalAttribute">
        <eLiterals name="CONSTANT"/>
        <eLiterals name="RETAIN" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalVarDeclaration" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="varSpec" lowerBound="1"
            eType="#//core/declarations/GlobalVarSpec" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/declarations/GlobalVarSpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Var2SpecInitDecl" eSuperTypes="#//core/declarations/NamedVariableDeclaration #//core/declarations/VarInitDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="specInit" lowerBound="1"
            eType="#//core/declarations/Var2SpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgramAccessDeclaration" eSuperTypes="#//core/literals/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//core/types/NonGenericType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
            eType="#//core/variables/SymbolicVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//core/declarations/Direction"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Direction">
        <eLiterals name="READ_ONLY"/>
        <eLiterals name="READ_WRITE" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FBInstance" eSuperTypes="#//core/declarations/VarInitDeclaration #//core/declarations/VarDeclarationOnly #//core/literals/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//core/types/StructureInit"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//core/pous/AbstractFunctionBlockDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlockType"
            lowerBound="1" eType="#//core/pous/AbstractFunctionBlockDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExternalVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" lowerBound="1"
            eType="#//core/variables/GlobalVar" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="spec" lowerBound="1"
            eType="#//core/declarations/ExternalVarSpec" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayStructVarSpec" abstract="true"
          eSuperTypes="#//core/declarations/TempVarDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" lowerBound="1"
            eType="#//core/variables/NamedVariable" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SharedVarSpec" abstract="true" eSuperTypes="#//core/declarations/VarSpec #//core/declarations/ExternalVarSpec"/>
      <eClassifiers xsi:type="ecore:EClass" name="SingleByteStringVar" abstract="true"
          eSuperTypes="#//core/declarations/StringVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="SingleByteStringSpec" eSuperTypes="#//core/declarations/SingleByteStringVar #//core/declarations/StringSpecification"/>
      <eClassifiers xsi:type="ecore:EClass" name="StringVariable" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
            eType="#//core/literals/IntegerLiteral" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DoubleByteStringSpec" eSuperTypes="#//core/declarations/StringSpecification #//core/declarations/DoubleByteStringVar"/>
      <eClassifiers xsi:type="ecore:EClass" name="DoubleByteStringVar" abstract="true"
          eSuperTypes="#//core/declarations/StringVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="AccessDeclaration" abstract="true"
          eSuperTypes="#//core/literals/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//core/declarations/Direction"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//core/types/NonGenericType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRef" eType="#//core/configurations/ResourceDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SymbolicAccessPath" eSuperTypes="#//core/declarations/AccessDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="fbRef" eType="#//core/declarations/FBInstance"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="programRef" eType="#//core/configurations/ProgramConfiguration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
            eType="#//core/variables/SymbolicVariable" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceSpecificVarInit" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRef" lowerBound="1"
            eType="#//core/configurations/ResourceDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="programRef" lowerBound="1"
            eType="#//core/configurations/ProgramConfiguration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceSpecificVariable" abstract="true"
          eSuperTypes="#//core/declarations/InstanceSpecificVarInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableRef" lowerBound="1"
            eType="#//core/variables/NamedVariable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//core/variables/DirectVariable"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="specinit" lowerBound="1"
            eType="#//core/declarations/InstanceSpecificSpecInit" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceSpecificFB" eSuperTypes="#//core/declarations/InstanceSpecificVarInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="init" lowerBound="1"
            eType="#//core/types/StructureInit" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fbInstanceRef" lowerBound="1"
            eType="#//core/declarations/FBInstance"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExternalVarSpec" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalVarSpecInit" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceSpecificSpecInit" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="Var2SpecInit" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="Var1SpecInit" abstract="true" interface="true"
          eSuperTypes="#//core/declarations/Var2SpecInit"/>
      <eClassifiers xsi:type="ecore:EClass" name="NamedVariableDeclaration" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" lowerBound="1"
            eType="#//core/variables/NamedVariable" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LocatedVarSpecInit" abstract="true"
          eSuperTypes="#//core/declarations/GlobalVarSpecInit"/>
      <eClassifiers xsi:type="ecore:EClass" name="Var1Specification" abstract="true"
          interface="true"/>
    </eSubpackages>
    <eSubpackages name="pous" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core/pous"
        nsPrefix="pous">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains so called program organisation units (pou's)"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//core/pous/POU">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
            eType="#//core/declarations/FunctionVariableDeclaration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="returnDomain" lowerBound="1"
            eType="#//core/pous/FunctionReturnDomain"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
            eType="#//core/pous/FunctionBody" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionReturnDomain" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionBody" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockDeclaration" eSuperTypes="#//core/pous/AbstractFunctionBlockDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
            eType="#//core/declarations/FunctionBlockVariableDeclaration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
            eType="#//core/pous/FunctionBlockBody" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockBody" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="ProgramDeclaration" eSuperTypes="#//core/pous/POU">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
            eType="#//core/declarations/ProgramVariableDeclaration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
            eType="#//core/pous/FunctionBlockBody" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="POU" abstract="true" interface="true"
          eSuperTypes="#//core/LibraryElement #//core/literals/CommentableElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            volatile="true" defaultValueLiteral="st" derived="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AbstractFunctionBlockDeclaration"
          abstract="true" eSuperTypes="#//core/pous/POU"/>
      <eClassifiers xsi:type="ecore:EClass" name="BlackboxFunctionBlockDeclaration"
          eSuperTypes="#//core/pous/AbstractFunctionBlockDeclaration">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This class allows only var declarations for in, out and inout variables. Enables Blackbox functionality"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
            eType="#//core/declarations/IOVarDeclaration" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockPointer" eSuperTypes="#//core/declarations/ExternalVarSpec #//core/declarations/GlobalVarSpecInit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlockType"
            eType="#//core/pous/AbstractFunctionBlockDeclaration"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="configurations" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/core/configurations"
        nsPrefix="configurations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains configurations and instances of programs and instance specific initializations"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="ConfigurationDeclaration" eSuperTypes="#//core/LibraryElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="resources" lowerBound="1"
            upperBound="-1" eType="#//core/configurations/ResourceDeclaration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
            eType="#//core/declarations/ConfigurationVariableDeclaration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="access" eType="#//core/declarations/AccessVarContainer"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="instanceSpecificInits"
            eType="#//core/declarations/InstanceSpecificVarContainter" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalVarNames" upperBound="-1"
            eType="#//core/variables/GlobalVar" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ResourceDeclaration" eSuperTypes="#//core/literals/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" eType="#//core/declarations/ResourceVariableDeclaration"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="programConfigurations"
            lowerBound="1" upperBound="-1" eType="#//core/configurations/ProgramConfiguration"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="taskConfigurations"
            upperBound="-1" eType="#//core/configurations/TaskConfiguration" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalVarNames" upperBound="-1"
            eType="#//core/variables/GlobalVar" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="onHardwareResource"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgramConfiguration" eSuperTypes="#//core/literals/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="with" eType="#//core/configurations/TaskConfiguration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="program" lowerBound="1"
            eType="#//core/pous/ProgramDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="retain" eType="#//core/configurations/Retain"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="progConfElements" upperBound="-1"
            eType="#//core/configurations/ProgConfElement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TaskConfiguration" eSuperTypes="#//core/literals/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="single" eType="#//core/configurations/DataSource"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="interval" eType="#//core/configurations/DataSource"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="priority" lowerBound="1"
            eType="#//core/literals/IntegerLiteral" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalVarReference" eSuperTypes="#//core/configurations/DataSource #//core/configurations/DataSink #//core/configurations/ProgDataSource">
        <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
            eType="#//core/variables/GlobalVar"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="structureElementName"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgramOutputReference" eSuperTypes="#//core/configurations/DataSource">
        <eStructuralFeatures xsi:type="ecore:EReference" name="refernce" lowerBound="1"
            eType="#//core/variables/SymbolicVariable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Retain">
        <eLiterals name="RETAIN"/>
        <eLiterals name="NON_RETAIN" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgConfElement" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="FBTask" eSuperTypes="#//core/configurations/ProgConfElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="with" lowerBound="1"
            eType="#//core/configurations/TaskConfiguration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlock" lowerBound="1"
            eType="#//core/pous/FunctionBlockDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgCnxn" eSuperTypes="#//core/configurations/ProgConfElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="progDataSourceVar"
            lowerBound="1" eType="#//core/variables/SymbolicVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="progDataSourceValue"
            lowerBound="1" eType="#//core/configurations/ProgDataSource" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSinkVar" eType="#//core/variables/SymbolicVariable"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSinkValue" lowerBound="1"
            eType="#//core/configurations/DataSink" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProgDataSource" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="DataSink" abstract="true" interface="true"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="languages" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/languages"
      nsPrefix="languages">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="contains addon packages for core package to model whole programs valid to iec 61131"/>
    </eAnnotations>
    <eSubpackages name="st" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/languages/st"
        nsPrefix="st">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="contains language constructs of structured text, addon package to the core package for modeling st programs"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//languages/st/PrimaryExpressionValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//languages/st/Operator"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Operator">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpression" eSuperTypes="#//languages/st/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="unaryOperator" eType="#//languages/st/UnaryOperator"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            eType="#//languages/st/PrimaryExpressionValue" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UnaryOperator">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpressionValue" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionInvocation" eSuperTypes="#//languages/st/PrimaryExpressionValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="paramAssignmentList"
            lowerBound="1" upperBound="-1" eType="#//languages/st/ParamAssignment"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
            eType="#//core/pous/FunctionDeclaration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParamAssignment" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="StatementList" eSuperTypes="#//core/pous/FunctionBody #//core/pous/FunctionBlockBody">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statments" lowerBound="1"
            upperBound="-1" eType="#//languages/st/Statement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="AssignmentStatement" eSuperTypes="#//languages/st/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
            eType="#//core/variables/Variable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            eType="#//languages/st/Expression"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SubprogramControlStatement" abstract="true"
          interface="true" eSuperTypes="#//languages/st/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="SelectionStatement" abstract="true"
          interface="true" eSuperTypes="#//languages/st/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="IterationStatement" abstract="true"
          interface="true" eSuperTypes="#//languages/st/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="NILStatement" eSuperTypes="#//languages/st/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="FBInvocation" eSuperTypes="#//languages/st/SubprogramControlStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlock" lowerBound="1"
            eType="#//core/declarations/FBInstance"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="paramAssignmentList"
            upperBound="-1" eType="#//languages/st/ParamAssignment" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//languages/st/SubprogramControlStatement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ParamImplication" eSuperTypes="#//languages/st/ParamAssignment">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="leftSide" lowerBound="1"
            eType="#//core/variables/SymbolicVariable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rightSide" lowerBound="1"
            eType="#//core/variables/Variable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParamExpression" eSuperTypes="#//languages/st/ParamAssignment">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" eType="#//core/variables/SymbolicVariable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//languages/st/SelectionStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="elsif" eType="#//languages/st/IfStatement"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//languages/st/StatementList"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//languages/st/Else"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CaseStatement" eSuperTypes="#//languages/st/SelectionStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//languages/st/Else"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="caseElements" lowerBound="1"
            upperBound="-1" eType="#//languages/st/CaseElement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Else">
        <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1"
            eType="#//languages/st/StatementList"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CaseElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="caseList" lowerBound="1"
            upperBound="-1" eType="#//languages/st/CaseListElement" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="statementList" lowerBound="1"
            eType="#//languages/st/StatementList" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CaseListElement" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//languages/st/IterationStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="by" eType="#//languages/st/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="do" lowerBound="1"
            eType="#//languages/st/StatementList" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//languages/st/IterationStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="do" lowerBound="1"
            eType="#//languages/st/StatementList" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RepeatStatement" eSuperTypes="#//languages/st/IterationStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
            eType="#//languages/st/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="do" lowerBound="1"
            eType="#//languages/st/StatementList" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExitStatement" eSuperTypes="#//languages/st/IterationStatement"/>
      <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//languages/st/PrimaryExpressionValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
            eType="#//core/variables/Variable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumeratedValueRef" eSuperTypes="#//languages/st/PrimaryExpressionValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="enumValue" eType="#//core/types/EnumeratedValue"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="il" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/languages/il"
        nsPrefix="il">
      <eClassifiers xsi:type="ecore:EClass" name="InstructionList" eSuperTypes="#//core/pous/FunctionBody #//core/pous/FunctionBlockBody">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Entry point for instruction list."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" lowerBound="1"
            upperBound="-1" eType="#//languages/il/Instruction" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true" interface="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//languages/il/IlLabel"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleOperation" abstract="true"
          interface="true" eSuperTypes="#//languages/il/Instruction #//languages/il/SimpleInstruction"/>
      <eClassifiers xsi:type="ecore:EClass" name="JumpOperation" eSuperTypes="#//languages/il/Instruction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="JumpOperatorLabel"
            lowerBound="1" eType="#//languages/il/Instruction"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="JumpOperator" lowerBound="1"
            eType="#//languages/il/JumpOperator"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IlExpression" eSuperTypes="#//languages/il/Instruction #//languages/il/SimpleInstruction">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExprOperator" lowerBound="1"
            eType="#//languages/il/ExprOperator" defaultValueLiteral="AND"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//languages/il/Operand"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="simpleInstructionList"
            upperBound="-1" eType="#//languages/il/SimpleInstruction" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IlFBCall" eSuperTypes="#//languages/il/Instruction">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="callOperator" lowerBound="1"
            eType="#//languages/il/CallOperator"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fbName" lowerBound="1"
            eType="#//core/declarations/FBInstance"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fbCallParam" lowerBound="1"
            eType="#//languages/il/FBCallParamPlaceHolder" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IlFormalFunctCall" eSuperTypes="#//languages/il/Instruction #//languages/il/SimpleInstruction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="functionName" lowerBound="1"
            eType="#//core/pous/FunctionDeclaration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="paramList" eType="#//languages/il/ParamList"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReturnOperatorPlaceHolder" eSuperTypes="#//languages/il/Instruction">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnOperator" lowerBound="1"
            eType="#//languages/il/ReturnOperator"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SimpleOperator">
        <eLiterals name="LD"/>
        <eLiterals name="LDN" value="1"/>
        <eLiterals name="ST" value="2"/>
        <eLiterals name="STN" value="4"/>
        <eLiterals name="NOT" value="5" literal="NOT"/>
        <eLiterals name="S" value="6" literal="S"/>
        <eLiterals name="R" value="7"/>
        <eLiterals name="S1" value="8" literal="S1"/>
        <eLiterals name="R1" value="9"/>
        <eLiterals name="CLK" value="10" literal="CLK"/>
        <eLiterals name="CU" value="11" literal="CU"/>
        <eLiterals name="CD" value="12" literal="CD"/>
        <eLiterals name="PV" value="13" literal="PV"/>
        <eLiterals name="IN" value="14" literal="IN"/>
        <eLiterals name="PT" value="15" literal="PT"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ExprOperator">
        <eLiterals name="AND"/>
        <eLiterals name="OR" value="1"/>
        <eLiterals name="XOR" value="2"/>
        <eLiterals name="ANDN" value="3"/>
        <eLiterals name="ORN" value="4"/>
        <eLiterals name="XORN" value="5"/>
        <eLiterals name="ADD" value="6"/>
        <eLiterals name="SUB" value="7"/>
        <eLiterals name="MUL" value="8"/>
        <eLiterals name="DIV" value="9"/>
        <eLiterals name="MOD" value="10"/>
        <eLiterals name="GT" value="11"/>
        <eLiterals name="GE" value="12"/>
        <eLiterals name="EQ" value="13"/>
        <eLiterals name="LT" value="14"/>
        <eLiterals name="LE" value="15"/>
        <eLiterals name="NE" value="16"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Operand" abstract="true" interface="true"
          eSuperTypes="#//languages/il/ParamAssignmentOperand"/>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleInstruction" abstract="true"
          interface="true" eSuperTypes="#//languages/il/ParamAssignmentOperand"/>
      <eClassifiers xsi:type="ecore:EEnum" name="JumpOperator">
        <eLiterals name="JMP"/>
        <eLiterals name="JMPC" value="1"/>
        <eLiterals name="JMPCN" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParamInstruction" abstract="true"
          interface="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableName" lowerBound="1"
            eType="#//core/variables/NamedVariable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IlParamAssignment" eSuperTypes="#//languages/il/ParamInstruction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
            eType="#//languages/il/ParamAssignmentOperand" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IlParamOutAssignment" eSuperTypes="#//languages/il/ParamInstruction">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="isLastElementInList"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="NOT" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
            eType="#//core/variables/Variable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="CallOperator">
        <eLiterals name="CAL"/>
        <eLiterals name="CALC" value="1"/>
        <eLiterals name="CALCN" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ReturnOperator">
        <eLiterals name="RET"/>
        <eLiterals name="RETC" value="1"/>
        <eLiterals name="RETCN" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParamAssignmentOperand" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="ParamList" eSuperTypes="#//languages/il/FBCallParamPlaceHolder">
        <eStructuralFeatures xsi:type="ecore:EReference" name="paramInstructions"
            lowerBound="1" upperBound="-1" eType="#//languages/il/ParamInstruction"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OperandList" eSuperTypes="#//languages/il/FBCallParamPlaceHolder">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operands" lowerBound="1"
            upperBound="-1" eType="#//languages/il/Operand" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FBCallParamPlaceHolder" abstract="true"
          interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="IlLabel" eSuperTypes="#//core/literals/NamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="OperandConstant" eSuperTypes="#//languages/il/Operand">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constant" lowerBound="1"
            eType="#//core/literals/Constant" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OperandEnumeratedValue" eSuperTypes="#//languages/il/Operand">
        <eStructuralFeatures xsi:type="ecore:EReference" name="enumeratedValue" lowerBound="1"
            eType="#//core/types/EnumeratedValue"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OperandVariable" eSuperTypes="#//languages/il/Operand">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
            eType="#//core/variables/Variable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleOperationOperand" eSuperTypes="#//languages/il/SimpleOperation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="hasOnlyOneOperator"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="SimpleOperator" eType="#//languages/il/SimpleOperator"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExprOperator" eType="#//languages/il/ExprOperator"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//languages/il/Operand"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleOperationFunction" eSuperTypes="#//languages/il/SimpleOperation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operandList" eType="#//languages/il/OperandList"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="functionName" lowerBound="1"
            eType="#//core/pous/FunctionDeclaration"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="extensions" nsURI="http://iem.fraunhofer.de/m4a/iec61131/1.0/extensions"
      nsPrefix="extensions">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="contains modelings to include ready compiled program bricks"/>
    </eAnnotations>
  </eSubpackages>
</ecore:EPackage>
