package de.uni_paderborn.fujaba.muml.componentinstanceconfiguration.diagram.custom.parsers;

import de.uni_paderborn.fujaba.muml.componentinstanceconfiguration.diagram.parsers.HybridPortInstanceLabelExpressionLabelParser5043;

public class CustomHybridPortInstanceLabelExpressionLabelParser5043 extends
		HybridPortInstanceLabelExpressionLabelParser5043 {
}