/**
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.formatting2;

import com.google.inject.Inject;
import de.fraunhofer.iem.projectPlanning.Assignment;
import de.fraunhofer.iem.projectPlanning.Capability;
import de.fraunhofer.iem.projectPlanning.Employee;
import de.fraunhofer.iem.projectPlanning.Project;
import de.fraunhofer.iem.projectPlanning.ProjectPlan;
import de.fraunhofer.iem.projectPlanning.Rating;
import de.fraunhofer.iem.services.ProjectPlanningGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@SuppressWarnings("all")
public class ProjectPlanningFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ProjectPlanningGrammarAccess _projectPlanningGrammarAccess;
  
  protected void _format(final ProjectPlan projectPlan, @Extension final IFormattableDocument document) {
    EList<Capability> _capabilities = projectPlan.getCapabilities();
    for (final Capability capability : _capabilities) {
      document.<Capability>format(capability);
    }
    EList<Employee> _employees = projectPlan.getEmployees();
    for (final Employee employee : _employees) {
      document.<Employee>format(employee);
    }
    EList<Project> _projects = projectPlan.getProjects();
    for (final Project project : _projects) {
      document.<Project>format(project);
    }
    EList<Rating> _ratings = projectPlan.getRatings();
    for (final Rating rating : _ratings) {
      document.<Rating>format(rating);
    }
    EList<Assignment> _assignments = projectPlan.getAssignments();
    for (final Assignment assignment : _assignments) {
      document.<Assignment>format(assignment);
    }
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(projectPlan).keyword("capabilities:"), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(projectPlan).keyword("employees:"), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(projectPlan).keyword("projects:"), _function_2);
  }
  
  protected void _format(final Assignment assignment, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(assignment).keyword(";"), _function);
  }
  
  protected void _format(final Project project, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<Project>interior(project, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(project).keyword(":"), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(project).keyword(";"), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(project).keyword("requiresResources:"), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(project).keyword("requiresCapabilities:"), _function_4);
  }
  
  protected void _format(final Employee employee, @Extension final IFormattableDocument document) {
    EList<Rating> _ratings = employee.getRatings();
    for (final Rating rating : _ratings) {
      document.<Rating>format(rating);
    }
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<Employee>interior(employee, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(employee).keyword(":"), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(employee).keyword(";"), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(employee).keyword("ratesCapabilities:"), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(employee).keyword("hasCapabilities:"), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(this.textRegionExtensions.regionFor(employee).keyword("hasResources:"), _function_5);
  }
  
  protected void _format(final Rating rating, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(this.textRegionExtensions.regionFor(rating).keyword(";"), _function);
  }
  
  protected void _format(final Capability capability, @Extension final IFormattableDocument document) {
  }
  
  public void format(final Object assignment, final IFormattableDocument document) {
    if (assignment instanceof XtextResource) {
      _format((XtextResource)assignment, document);
      return;
    } else if (assignment instanceof Assignment) {
      _format((Assignment)assignment, document);
      return;
    } else if (assignment instanceof Capability) {
      _format((Capability)assignment, document);
      return;
    } else if (assignment instanceof Employee) {
      _format((Employee)assignment, document);
      return;
    } else if (assignment instanceof Project) {
      _format((Project)assignment, document);
      return;
    } else if (assignment instanceof ProjectPlan) {
      _format((ProjectPlan)assignment, document);
      return;
    } else if (assignment instanceof Rating) {
      _format((Rating)assignment, document);
      return;
    } else if (assignment instanceof EObject) {
      _format((EObject)assignment, document);
      return;
    } else if (assignment == null) {
      _format((Void)null, document);
      return;
    } else if (assignment != null) {
      _format(assignment, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(assignment, document).toString());
    }
  }
}
