/*
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.muml;

import org.eclipse.xtext.scoping.IScopeProvider;

import com.google.inject.Binder;
import com.google.inject.Provider;

import de.uni_paderborn.fujaba.muml.naming.CustomNameProvider;
import de.uni_paderborn.fujaba.muml.scoping.ActionLanguageScopeProvider;
import de.uni_paderborn.fujaba.muml.scoping.ActionLanguageScopeProviderFactory;
import de.uni_paderborn.fujaba.muml.scoping.IActionLanguageScopeProvider;



/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActionLanguageRuntimeModule extends de.uni_paderborn.fujaba.muml.AbstractActionLanguageRuntimeModule {
	
	public Provider<IScopeProvider> provideIScopeProvider() {
		return new ActionLanguageScopeProviderFactory();
	}
	
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return null;
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return CustomNameProvider.class;
	}
	
	public Class<? extends IActionLanguageScopeProvider> bindIActionLanguageScopeProvider() {
		return ActionLanguageScopeProvider.class;
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.requestStaticInjection(ActionLanguageScopeProviderFactory.class);
	}

}
