<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lookup" nsURI="http://www.eclipse.org/ocl/2015/Lookup" nsPrefix="lookup">
  <eClassifiers xsi:type="ecore:EClass" name="Environment" instanceClassName="org.eclipse.ocl.pivot.internal.lookup.LookupEnvironment">
    <eOperations name="addElement" lowerBound="1" eType="#//Environment">
      <eParameters name="element" lowerBound="1" eType="ecore:EClass Pivot.ecore#//NamedElement"/>
    </eOperations>
    <eOperations name="addElement" lowerBound="1" eType="#//Environment">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType ../model-gen/oclstdlib.ecore#//String"/>
      <eParameters name="element" lowerBound="1" eType="ecore:EClass Pivot.ecore#//NamedElement"/>
    </eOperations>
    <eOperations name="addElements" lowerBound="1" eType="#//Environment">
      <eParameters name="elements" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType ../model-gen/oclstdlib.ecore#//Collection">
          <eTypeArguments eClassifier="ecore:EClass Pivot.ecore#//NamedElement"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="hasFinalResult" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="nestedEnv" lowerBound="1" eType="#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedElements" upperBound="-1"
        eType="ecore:EClass Pivot.ecore#//NamedElement"/>
  </eClassifiers>
</ecore:EPackage>
