#ifndef MUML_DDS_IDL
#define MUML_DDS_IDL

  struct DDS_MessagesorderForPS_Messages;
  struct DDS_MessagesnoOrder_Messages;
  struct DDS_MessagesdoneOrder_Messages;
  struct DDS_MessagessimpleOrder_Messages;
  struct DDS_MessagesgetOrder_Messages;

#pragma DCPS_DATA_TYPE "DDS_MessagesorderForPS_Messages"
  struct DDS_MessagesorderForPS_Messages {
    long receiverPsID;
    long orderID;
    long ingredientID;
    long amount;
  };

#pragma DCPS_DATA_TYPE "DDS_MessagesnoOrder_Messages"
  struct DDS_MessagesnoOrder_Messages {
    long receiverPsID;
  };

#pragma DCPS_DATA_TYPE "DDS_MessagesdoneOrder_Messages"
  struct DDS_MessagesdoneOrder_Messages {
    long orderID;
  };

#pragma DCPS_DATA_TYPE "DDS_MessagessimpleOrder_Messages"
  struct DDS_MessagessimpleOrder_Messages {
    long orderID;
    long ingredientID;
    long amount;
  };

#pragma DCPS_DATA_TYPE "DDS_MessagesgetOrder_Messages"
  struct DDS_MessagesgetOrder_Messages {
    long psID;
    long producibleIngredients;
  };
#endif 
