<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="psm" nsURI="http://www.fujaba.de/muml/psm/0.1" nsPrefix="psm">
  <eAnnotations source="http://www.eclipse.org/edapt">
    <details key="historyURI" value="../../de.uni_paderborn.fujaba.muml/model/muml.history"/>
  </eAnnotations>
  <eSubpackages name="deployment" nsURI="http://www.fujaba.de/muml/deployment/0.3.11"
      nsPrefix="deployment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Deployment" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement ../../org.storydriven.core/model/core.ecore#//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Deployment exists in the software lifecycle to bridge the gap between what a software developer could know about the execution environment and what the environment's developer could know about the deployable software.\footnote{C. Szyperski, Foreword to Proceedings of Component Deployment, IFIP/ACM Working Conference, Berlin 2002}"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLinks" upperBound="-1"
          eType="#//deployment/CommunicationLink" containment="true" eOpposite="#//deployment/CommunicationLink/deployment">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A Deployment contains CommunicationLinks which are used to connect HardwarePorts."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareNodes" lowerBound="1"
          upperBound="-1" eType="#//deployment/HardwareNode" containment="true" eOpposite="#//deployment/HardwareNode/deployment">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A Deployment contains HardwareNodes which represents hardware resources like computational, communication, sensor, or actor."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstanceConfiguration"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ComponentInstanceConfiguration">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The componentInstanceConfiguration which contains the component instances which should be deployed to hardware nodes."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualityOfLinkServices"
          eType="#//deployment/LinkQualityOfService" containment="true" eOpposite="#//deployment/LinkQualityOfService/deployment">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Reference to all contained quality of services."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HardwareNode" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement ../../org.storydriven.core/model/core.ecore#//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="NoDeploymentOnActorOrSensor" value="(self.hardwareNodeKind &lt;> deployment::HardwareNodeKind::COMPUTATIONAL_RESOURCE) implies self.deployedInstances->isEmpty()"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A run-time computational resource which generally has at least memory and processing capabilities. &#xD;&#xA;Component instances may reside on hardware nodes if they are not a sensor or an actor."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="NoDeploymentOnActorOrSensor"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" lowerBound="1"
          eType="#//deployment/Deployment" eOpposite="#//deployment/Deployment/hardwareNodes">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Deployment which contains the HardwareNode."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hardwarePorts" upperBound="-1"
          eType="#//deployment/HardwarePort" containment="true" eOpposite="#//deployment/HardwarePort/hardwareNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A HardwareNode contains HardwarePorts to communicate with other HardwarePorts via a CommunicationLink."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployedInstances" upperBound="-1"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/ComponentInstance">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="ComponentInstances which are deployed to the HardwareNode."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardwareNodeKind" eType="#//deployment/HardwareNodeKind">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A HardwareNode is kind of a computational resource, a sensor, an actor, or a communication device like a router."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="HardwareNodeKind">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Different kinds of HardwareNodes. "/>
      </eAnnotations>
      <eLiterals name="COMPUTATIONAL_RESOURCE"/>
      <eLiterals name="SENSOR" value="2"/>
      <eLiterals name="ACTOR" value="1"/>
      <eLiterals name="COMMUNICATION" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HardwarePort" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement ../../org.storydriven.core/model/core.ecore#//CommentableElement ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//connector/ConnectorEndpoint">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Hardware ports  are used to communicate&#xD;&#xA;with other hardware nodes and with component instances."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareNode" lowerBound="1"
          eType="#//deployment/HardwareNode" eOpposite="#//deployment/HardwareNode/hardwarePorts">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Hardware nodes are hardware elements on which port instances could be deployed if they are not a sensor or an actor."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployedPortInstance"
          upperBound="-1" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/PortInstance">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="PortInstances which are deployed to the HardwarePort."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//deployment/HardwarePortDirectionKind"
          defaultValueLiteral="">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A HardwarePort is of kind in, out, or in/out. &#xD;&#xA;Depending on its kind it can receive, send, or receive and send messages. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLinks" upperBound="-1"
          eType="#//deployment/CommunicationLink" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="derivation" value="self.connectors->select(c | c.oclIsTypeOf(CommunicationLink)).oclAsType(CommunicationLink)->asOrderedSet()"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="CommunicationLinks which have the HardwarePort as connector endpoints."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationLink" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//connector/Connector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A communication link between hardware nodes and a target used for the deployment of connectors between component instances."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" lowerBound="1"
          eType="#//deployment/Deployment" eOpposite="#//deployment/Deployment/communicationLinks">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The deployment to which the link belongs to."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualityOfService" eType="#//deployment/LinkQualityOfService">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The quality of service which the link fullfills. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployedAssemblyInstances"
          upperBound="-1" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//instance/AssemblyConnectorInstance">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Used for the deployment of connectors between component instances."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hardwarePorts" upperBound="-1"
          eType="#//deployment/HardwarePort" changeable="false" volatile="true" transient="true"
          derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="derivation" value="self.connectorEndpoints->select(c | c.oclIsTypeOf(HardwarePort)).oclAsType(HardwarePort)->asOrderedSet()"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Derives all hardware ports which are endpoints of the communication link."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="HardwarePortDirectionKind">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A HardwarePort is of kind in, out, or in/out. &#xD;&#xA;Depending on its kind it can receive, send, or receive and send messages. "/>
      </eAnnotations>
      <eLiterals name="IN"/>
      <eLiterals name="OUT" value="1"/>
      <eLiterals name="IN_OUT" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkQualityOfService" eSuperTypes="../../org.storydriven.core/model/core.ecore#//CommentableElement ../../org.storydriven.core/model/core.ecore#//NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Quality of Service of a communication link. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="packetDelayVariation"
          eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Difference in end-to-end one-way delay between selected messages without lost messages."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="latency" eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml/model/muml.ecore#//valuetype/TimeValue"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The time from the source port sending a message to the destination port receiving it."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" eType="#//deployment/Deployment"
          eOpposite="#//deployment/Deployment/qualityOfLinkServices">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The deployment to which the service belongs."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
