<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtime"
    nsURI="http://www.fujaba.de/muml/model/runtime/0.3.1" nsPrefix="runtime">
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeComponentInstance" eSuperTypes="../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/instance/ComponentInstance #//RuntimeBehavioralElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeDiscretePortInstance" eSuperTypes="../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/instance/DiscretePortInstance #//RuntimeBehavioralElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleInstance" abstract="true" eSuperTypes="#//RuntimeBehavioralElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceOf" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/protocol/Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assembly" eType="#//RuntimeRoleAssembly"
        eOpposite="#//RuntimeRoleAssembly/roleInstances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageBuffer" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferSize" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//RuntimeMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeBehavioralElement"
        lowerBound="1" eType="#//RuntimeBehavioralElement" eOpposite="#//RuntimeBehavioralElement/messageBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealtimeStatechartInstance" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeBehavioralElement"
        eType="#//RuntimeBehavioralElement" eOpposite="#//RuntimeBehavioralElement/statechartInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceOf" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/realtimestatechart/RealtimeStatechart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="active" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/realtimestatechart/State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subRealtimeStatechartInstances"
        upperBound="-1" eType="#//RealtimeStatechartInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableBindings" upperBound="-1"
        eType="#//VariableBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeMessage" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//RuntimeParameter" containment="true" eOpposite="#//RuntimeParameter/message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeParameter" eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="#//RuntimeMessage" eOpposite="#//RuntimeMessage/parameters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//JavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableBinding" eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/behavior/Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//JavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeBehavioralElement" abstract="true"
      eSuperTypes="../../org.storydriven.core/model/core.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechartInstance" eType="#//RealtimeStatechartInstance"
        containment="true" eOpposite="#//RealtimeStatechartInstance/runtimeBehavioralElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageBuffer" eType="#//MessageBuffer"
        containment="true" eOpposite="#//MessageBuffer/runtimeBehavioralElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JavaObject" instanceClassName="java.lang.Object"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleRoleInstance" eSuperTypes="#//RoleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiRoleInstance" eType="#//MultiRoleInstance"
        eOpposite="#//MultiRoleInstance/subRoleInstances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiRoleInstance" eSuperTypes="#//RoleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subRoleInstances" upperBound="-1"
        eType="#//SingleRoleInstance" eOpposite="#//SingleRoleInstance/multiRoleInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeRoleAssembly" eSuperTypes="#//RuntimeAssemblyInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleInstances" lowerBound="2"
        upperBound="2" eType="#//RoleInstance" eOpposite="#//RoleInstance/assembly"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceOf" lowerBound="1"
        eType="ecore:EClass ../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/protocol/RoleConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeAssemblyInstance" abstract="true"
      eSuperTypes="../../org.storydriven.core/model/core.ecore#//ExtendableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientMessages" upperBound="-1"
        eType="#//MessageOnAssembly" containment="true" eOpposite="#//MessageOnAssembly/runtimeAssembly"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimePortInstanceAssembly" eSuperTypes="../../de.uni_paderborn.fujaba.muml.model/model/muml.ecore#//model/instance/AssemblyConnectorInstance #//RuntimeAssemblyInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageOnAssembly">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//RuntimeBehavioralElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="#//RuntimeMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeAssembly" lowerBound="1"
        eType="#//RuntimeAssemblyInstance" eOpposite="#//RuntimeAssemblyInstance/transientMessages"/>
  </eClassifiers>
</ecore:EPackage>
