/*
 * generated by Xtext
 */
package org.muml.graphviz.plain.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GraphvizPlainUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.muml.graphviz.plain.xtext.ui.internal.GraphvizPlainActivator.getInstance().getInjector("org.muml.graphviz.plain.xtext.GraphvizPlain");
	}
	
}
