/**
 *
 * $Id$
 */
package de.uni_paderborn.uppaal.expressions.validation;

import de.uni_paderborn.uppaal.expressions.Expression;
import de.uni_paderborn.uppaal.expressions.IncrementDecrementOperator;
import de.uni_paderborn.uppaal.expressions.IncrementDecrementPosition;

/**
 * A sample validator interface for {@link de.uni_paderborn.uppaal.expressions.IncrementDecrementExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IncrementDecrementExpressionValidator {
	boolean validate();

	boolean validateExpression(Expression value);
	boolean validatePosition(IncrementDecrementPosition value);
	boolean validateOperator(IncrementDecrementOperator value);
}
