<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ontology" nsURI="http://www.muml.org/ontology/1.0.0" nsPrefix="ontology">
  <eClassifiers xsi:type="ecore:EClass" name="OntologyExtension" eSuperTypes="../../org.muml.core/model/core.ecore#//Extension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ontologyReference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
