/**
 * generated by Xtext
 */
package org.muml.psm.allocation.ilp.lpsolve.xtext.ui.contentassist;

import org.muml.psm.allocation.ilp.lpsolve.xtext.ui.contentassist.AbstractLPSolveProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class LPSolveProposalProvider extends AbstractLPSolveProposalProvider {
}
