FROM debian:sid-slim

RUN  apt-get update && apt-get install -y build-essential libcurl4-gnutls-dev curl git binutils wget cmake pkg-config \
  && groupadd -r app && useradd -r -m -g app app \
  && apt-get autoremove -y && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ADD . /opt/app
ADD entrypoint.sh /usr/bin/
RUN  chmod +x /usr/bin/entrypoint.sh \
     && chown app:app -R /opt/app

WORKDIR /opt/app
USER app

RUN make

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD ./app
