/*
 * generated by Xtext 2.10.0
 */
package de.fraunhofer.iem.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSeminarScopeProvider extends DelegatingScopeProvider {
}
