/*
 * generated by Xtext
 */
package org.muml.psm.allocation.language.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AllocationSpecificationLanguageRuntimeModule extends org.muml.psm.allocation.language.xtext.AbstractAllocationSpecificationLanguageRuntimeModule {

}
