/*
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.graphviz.plain.xtext.ui.contentassist

import de.uni_paderborn.fujaba.graphviz.plain.xtext.ui.contentassist.AbstractGraphvizPlainProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GraphvizPlainProposalProvider extends AbstractGraphvizPlainProposalProvider {
}
