/**
 *
 * $Id$
 */
package de.uni_paderborn.fujaba.muml.testlanguage.validation;

import de.uni_paderborn.fujaba.muml.testlanguage.Node;
import de.uni_paderborn.fujaba.muml.testlanguage.Output;

/**
 * A sample validator interface for
 * {@link de.uni_paderborn.fujaba.muml.testlanguage.Input}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputValidator {
	boolean validate();

	boolean validateSource(Output value);

	boolean validateNode(Node value);

	boolean validateOptional(boolean value);

	boolean validateDataType(Class<?> value);
}
