/*
* generated by Xtext
*/
package de.uni_paderborn.uppaal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UppaalXMLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/uni_paderborn/uppaal/parser/antlr/internal/InternalUppaalXML.tokens");
	}
}
