<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basicSDD" nsURI="http://www.fujaba.de/muml/verification/sdd/basicSDD/0.4.0"
    nsPrefix="basicSDD">
  <eClassifiers xsi:type="ecore:EClass" name="StoryDecisionDiagram" eSuperTypes="../../de.uni_paderborn.fujaba.muml.verification.sdd/model/sdd.ecore#//AbstractStoryDecisionDiagram"/>
  <eClassifiers xsi:type="ecore:EClass" name="StoryPatternNode" eSuperTypes="../../de.uni_paderborn.fujaba.muml.verification.sdd/model/sdd.ecore#//PatternNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="ecore:EClass ../../org.storydriven.storydiagrams/model/storydiagrams.ecore#//patterns/StoryPattern"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
