/**
 * generated by Xtext 2.11.0
 */
package de.fraunhofer.iem.projectPlanning.impl;

import de.fraunhofer.iem.projectPlanning.Capability;
import de.fraunhofer.iem.projectPlanning.ProjectPlanningPackage;
import de.fraunhofer.iem.projectPlanning.Rating;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rating</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.iem.projectPlanning.impl.RatingImpl#getCapability <em>Capability</em>}</li>
 *   <li>{@link de.fraunhofer.iem.projectPlanning.impl.RatingImpl#getRating <em>Rating</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RatingImpl extends MinimalEObjectImpl.Container implements Rating
{
  /**
   * The cached value of the '{@link #getCapability() <em>Capability</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapability()
   * @generated
   * @ordered
   */
  protected Capability capability;

  /**
   * The default value of the '{@link #getRating() <em>Rating</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRating()
   * @generated
   * @ordered
   */
  protected static final int RATING_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRating() <em>Rating</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRating()
   * @generated
   * @ordered
   */
  protected int rating = RATING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RatingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProjectPlanningPackage.Literals.RATING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Capability getCapability()
  {
    if (capability != null && capability.eIsProxy())
    {
      InternalEObject oldCapability = (InternalEObject)capability;
      capability = (Capability)eResolveProxy(oldCapability);
      if (capability != oldCapability)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ProjectPlanningPackage.RATING__CAPABILITY, oldCapability, capability));
      }
    }
    return capability;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Capability basicGetCapability()
  {
    return capability;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCapability(Capability newCapability)
  {
    Capability oldCapability = capability;
    capability = newCapability;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectPlanningPackage.RATING__CAPABILITY, oldCapability, capability));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getRating()
  {
    return rating;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRating(int newRating)
  {
    int oldRating = rating;
    rating = newRating;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectPlanningPackage.RATING__RATING, oldRating, rating));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProjectPlanningPackage.RATING__CAPABILITY:
        if (resolve) return getCapability();
        return basicGetCapability();
      case ProjectPlanningPackage.RATING__RATING:
        return getRating();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProjectPlanningPackage.RATING__CAPABILITY:
        setCapability((Capability)newValue);
        return;
      case ProjectPlanningPackage.RATING__RATING:
        setRating((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProjectPlanningPackage.RATING__CAPABILITY:
        setCapability((Capability)null);
        return;
      case ProjectPlanningPackage.RATING__RATING:
        setRating(RATING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProjectPlanningPackage.RATING__CAPABILITY:
        return capability != null;
      case ProjectPlanningPackage.RATING__RATING:
        return rating != RATING_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (rating: ");
    result.append(rating);
    result.append(')');
    return result.toString();
  }

} //RatingImpl
