/**
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.graphviz.xtext.ui.contentassist;

import de.uni_paderborn.fujaba.graphviz.xtext.ui.contentassist.AbstractPlainProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PlainProposalProvider extends AbstractPlainProposalProvider {
}
