/**
 *
 * $Id$
 */
package de.uni_paderborn.uppaal.templates.validation;

import de.uni_paderborn.uppaal.expressions.Expression;

import de.uni_paderborn.uppaal.templates.Location;
import de.uni_paderborn.uppaal.templates.Selection;
import de.uni_paderborn.uppaal.templates.Synchronization;
import de.uni_paderborn.uppaal.templates.Template;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_paderborn.uppaal.templates.Edge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EdgeValidator {
	boolean validate();

	boolean validateSource(Location value);
	boolean validateTarget(Location value);
	boolean validateParentTemplate(Template value);
	boolean validateGuard(Expression value);
	boolean validateUpdate(EList<Expression> value);
	boolean validateSynchronization(Synchronization value);
	boolean validateSelection(EList<Selection> value);
}
