/*
* generated by Xtext
*/
package de.uni_paderborn.fujaba.graphviz.xtext.ui.outline;

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class PlainOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {
	
}
