/**
 *
 * $Id$
 */
package de.uni_paderborn.uppaal.declarations.system.validation;

import de.uni_paderborn.uppaal.templates.AbstractTemplate;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_paderborn.uppaal.declarations.system.InstantiationList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstantiationListValidator {
	boolean validate();

	boolean validateTemplate(EList<AbstractTemplate> value);
}
