/**
 * generated by Xtext
 */
package de.uni_paderborn.fujaba.muml.verification.uppaal.ui.contentassist;

import de.uni_paderborn.fujaba.muml.verification.uppaal.ui.contentassist.AbstractMtctlProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MtctlProposalProvider extends AbstractMtctlProposalProvider {
}
